### ISSUE TITLE
Is it possible to combine this extension with geo IP ?

### ISSUE THREAD

**Issue by offline-online** [codemix/yii2-localeurls#10]
So if user from France come ti visit my site I would like to load fr language. If user from UK comes to my site I would like to load en-uk language. It seems that this extension is recognizing geo ip https://github.com/rmrevin/yii2-geoip, put is it possible to combine this ext with yours ? I am already using your extension in my website and it is amazing, but now I need to be able to detect location of the user and load language based on that. Is it possible ? Thanks for your great work !

EDIT: so when user comes to my site for the first time, I want to load language based on his location, but he should still be able to chose other languages that app is offering to him via this extension.

**Comment by mikehaertl** [comment]
I don't think that this option is really a good idea. We should trust the browser about the preferred user language. geoip tells you the *location* of someone, but not about the *language* of that person (could be a tourist on a visit?)

Apart from that I also think that this would be out of scope of this extension.
