### ISSUE TITLE
Ajax Requests redirect to the page

### ISSUE THREAD

**Issue by newscloud** [codemix/yii2-localeurls#103]
Hi, I have 25+ or so Ajax requests. If default English is selected, the URL path is https://mydomain.com/ajax/call?id=122... that works fine.

If another language is selected, e.g. https://mydomain.com/ru/ajax/call?id=122, the browser lands on the page of the ajax request. It doesn't return to the calling page. In other words, the locale url seems to break the ajax request. 

If I manually try to add the current language code to the outbound ajax request, this happens,
https://mydomain.com/ru/ru/ajax/call?id=122 

If I try to add the ajax calls to the ignore arrays, e.g.
ignoreLanguageUrlPatterns' => [
                // route pattern => url pattern
                '#^ajax/call#' => '#^ajax/call#',
It's not working. It still moves the browser to the ajax page. And, I don't want to manually have to include 25 AJAX calls into this list if I can avoid it.

I'm very stuck right now. Please let me know what you think.

**Comment by samdark** [comment]
> If I manually try to add the current language code to the outbound ajax request, this happens,
https://mydomain.com/ru/ru/ajax/call?id=122

I've encountered similar behavior for non-AJAX requests. Here's a good example: http://yiipowered.com/ru/

I guess something alike happens in @newscloud case.

**Comment by newscloud** [comment]
p.s. I first discovered the problem on my live site after I'd deployed the language routing. I had to back it out today.

What was first happening, my ajax calls use relative paths ... and always have worked. But with the yii2-localeurl, it was making calls to (I think)https:///ajax/call?id=222&... ... with this extension, it created a path that the browser interpreted as absolute but with no domain name. Whereas with the extension, all the ajax calls failed.

I tried working around it by making absolute calls ... that's when I ran into the stuff I described up above.

**Comment by mikehaertl** [comment]
> ... the browser lands on the page of the ajax request. It doesn't return to the calling page.

@newscloud I don't really understand what that means. Could you rather give an example like this:

 * Which URL did you request?
 * What did you expected to happen?
 * What happened instead?

Please also show the full `urlManager` configuration especially whether you use `UrlNormalizer` or something.

**Comment by mikehaertl** [comment]
@samdark I agree to @newscloud that your issue sounds different. Could you do me a favor and check, since which release this happens? I've done quite some refactoring lately due to the new UrlNormalizer (which to be honest to me is some of the not so nice pieces of code in yii2.) Feel free to open another issue so we can discuss the problem there.

**Comment by samdark** [comment]
@mikehaertl happens since I've started using the extension so I guess it always was like that.

**Comment by samdark** [comment]
I've checked latest version and it seems it's fixed there...

**Comment by samdark** [comment]
@newscloud could you check with 1.4.10?

**Comment by mikehaertl** [comment]
@samdark Which version are you using? And do you use `UrlNormalizer`? We now really test all thinkable configurations and an error like yours should have popped up a long time ago.

**Comment by samdark** [comment]
I think it's the same issue but I've created a separate ticket just in case: 104

**Comment by samdark** [comment]
@newscloud try updating to latest version and cleaning up browser cache.

**Comment by newscloud** [comment]
@mikehaertl just back. The Ajax request is generated from JQuery. Expected behavior is an ajax request to the server which returns JSON. It repros on all Ajax requests as I described above.

Here is the urlManager config for frontend:
`'urlManager' => [
            //'class' => 'yii\web\UrlManager', // overloaded by codemix
            'class' => 'codemix\localeurls\UrlManager',
            // List all supported languages and include your app's default language.
            'languages' => ['en','es','ru','fr','de','ar','pt','ja','ko','hi'],//'zh-CN'
            'enableDefaultLanguageUrlCode' => false,
            'enableLanguagePersistence' => true,
            'enablePrettyUrl' => true,
            'showScriptName' => false,
            'ignoreLanguageUrlPatterns' => [
                // route pattern => url pattern
                '#^site/auth#' => '#^site/auth#',
                '#^address/import#' => '#^address/import#',
                '#^mailgun-notification/store#' => '#mailgun-notification/store#',
            ],
            //'enableStrictParsing' => false,
            'rules' => [
              'place' => 'place',
              'place/yours' => 'place/yours',
              'place/create' => 'place/create',
              'place/create_geo' => 'place/create_geo',
              'place/create_place_google' => 'place/create_place_google',
              'place/view/<id:\d+>' => 'place/view',
              'place/update/<id:\d+>' => 'place/update',
              'place/<slug>' => 'place/slug',
              '<controller:\w+>/<id:\d+>' => '<controller>/view',
              '<controller:\w+>/<action:\w+>/<id:\d+>' => '<controller>/<action>',
              'daemon/<action>' => 'daemon/<action>', // incl eight char action
              'site/<action>' => 'site/<action>', // incl eight char action
              'features' => 'site/features',
              'about' => 'site/about',
              'cfide|wp-login|wp-admin' => 'site/neverland',
              '<username>/<identity:[A-Za-z0-9_-]{8}>' => 'meeting/identity',
              'meeting' => 'meeting',
              'friend' => 'friend',
              'reminder' => 'reminder',
              'ticket' => 'ticket',
              'user-contact' => 'user-contact',
              'user-profile' => 'user-profile',
              'user-setting' => 'user-setting',
              '<username>' => 'meeting/scheduleme',
              // note - currently actions with 8 letters and no params will fail
              '<controller:\w+>/<action:\w+>' => '<controller>/<action>',
            ],
        ],`

The Jquery request looks like this:
#url_prefix.val() on the live server is blank. It's used for local development.

`$.ajax({
     url: $('#url_prefix').val()+'/meeting-place/choose',
     data: {id:   $('#meeting_id').val(), 'val': current_id},
     success: function(data) {
       displayNotifier('chooseplace');
       refreshSend();
       refreshFinalize();
       return true;
     }
  });`

The controller code looks like this
`public function actionChoose($id,$val) {
      Yii::$app->response->format = \yii\web\Response::FORMAT_JSON;
    ` 
Please let me know what else you need.

p.s. @samdark I believe I had just run composer update on the local and server when I installed the yii2-localeurl changes.

**Comment by mikehaertl** [comment]
@newscloud This extension does very simple things, nothing is really specific to AJAX. So your jQuery code is not relevant to the issue. It would help a lot if you could boil down the problem to the 3 points I've mentioned above here: https://github.com/codemix/yii2-localeurls/issues/103#issuecomment-292863184. By 1) I mean a really concrete URL, not some jQuery code like `$('#url_prefix')...`.

In the worst case the extension creates a 302 redirect. If that breaks your jQuery requests, you should find out why the redirect happens. Please understand that I can't help you with this.

**Comment by newscloud** [comment]
@mikehaertl I gave you example urls in the first post. All Ajax requests to urls don't return Json to the calling page they redirect and land to the Ajax controller page breaking the site. 

Do you need to see video? 

The only time it works is if it's  the default language and no language code appears in the URL. As soon as a language is chosen Ajax requests break.

**Comment by newscloud** [comment]
Ps wouldn't the extension throwing a redirect break an Ajax request?

**Comment by mikehaertl** [comment]
@newscloud I can only repeat what I've already said. If used correctly (language code in request URL) there should be no redirect at all. If you can't use those URLs in your AJAX requests and there is a redirect and this breaks your AJAX requests, I can't really help you. You then either need to exclude those requests with the ignore config or fix your js. The extension does not mess around with the response format. So whatever you set in your controller is what you should see in the response.

I recommend, that you maybe use a tool like `curl` to do some debugging. This really helps a lot to see what *really* is sent by the server. E.g. `curl -I http://...` will show you all response headers. If the response is not correctly handled as JSON this should help you to find out, why.

**Comment by newscloud** [comment]
@mikehaertl that actually helps me. So, you're saying that AJAX requests must use the current language code prefix in the URL or they won't work? So, in other words, the controller building the first page needs to set the language code as a hidden HTML input variable for the ajax call or the ajax call must pick it up from the current URL and parse it out.

**Comment by newscloud** [comment]
@mikehaertl @samdark WooT! that was the breakthrough Mike. I thought AJAX calls without a language code would pass through since the default language url doesn't use a language code. Ajax calls don't need to be language specific in my site. 

But, changing the jquery url_prefix to include the current language code fixed things.

You can try it out at [https://simpleplanner.io](https://simpleplanner.io) The home page has a switcher at the top. Once you sign up or log in, the switcher is at the bottom ... and on that page there is much more ajax to see working.
