### ISSUE TITLE
redirect HTTP status code

### ISSUE THREAD

**Issue by enepochatova** [codemix/yii2-localeurls#107]
Hello!

There is a question: your redirectToLanguage() function uses only 302 redirect by default. But we need 301 code for our cases. Could it become configurable? Maybe with using of normalizer 'action' setting or its own. 

Thank you!

**Comment by mikehaertl** [comment]
@enepochatova We've discussed this before and found that it's not as trivial as it sounds. See my comment here: https://github.com/codemix/yii2-localeurls/issues/95#issuecomment-288415228

**Comment by mikehaertl** [comment]
Closing this as there was no further feedback.
