### ISSUE TITLE
Case sensitivity

### ISSUE THREAD

**Issue by nikazooz** [codemix/yii2-localeurls#108]
First of all, thanks for the awesome package. :)

I was wondering if there is a reason why in `matchCode` method the second part of the code (usually the country) is changed to uppercase?

The reason I ask is because I need to configure languages with different scripts (f.e. "sr-Latn"). Currently this would be detected as "sr-LATN", which is not what I want.

**Comment by mikehaertl** [comment]
Which code do you mean? The one in the URL or the value of `Yii::$app->language`? For the former, the value adheres to the standard, see http://www.yiiframework.com/doc-2.0/guide-tutorial-i18n.html#locale. For the latter our main principle is to only use lower case letters in URLs. If you don't want that you can set `keepUppercaseLanguageCode` to `true` (see https://github.com/codemix/yii2-localeurls#language-configuration).

**Comment by mikehaertl** [comment]
Sorry, please exchange "former" and "latter" in my explanation above. :)

**Comment by nikazooz** [comment]
The one in URL is good as is. Suppose there is "sr-Latn" in configuration, and that's the language I want, if I go to f.e. "http:/{domain}.{tld}/sr-latn/", the language that set is "sr-LATN". The mentioned standard doesn't say anything about script code, just language code and uppercase country code in format of ll-CC.

**Comment by mikehaertl** [comment]
Hmm, I see. To be honest I wasn't aware of this specific code. It seems to be an exception to the other codes which are always in uppercase. Not sure, why the yii2 core devs made this decision. I also can't find `Latn` in the list of ISO 3166-1 codes. Frankly speaking, I think they got it wrong - and now I have another problem to deal with. :unamused:

I'll see, what I can do.

**Comment by mikehaertl** [comment]
@nikazooz Can you show me, what the browser sends as accepted language in this case? I.e. what are the exact values in `Yii::$app->request->getAcceptableLanguages()`?

**Comment by nikazooz** [comment]
I don't think that browsers have such options, just language or language-COUNTRY. Maybe that's the reason. Also, it's not used that often, at least I haven't seen it. It's an unfortunate circumstance that I have to support different scripts for the same language...

Script codes: http://www.unicode.org/iso15924/iso15924-codes.html

I'll figure something out for this rare use case. I was interested if something like that was already possible.
Thanks anyway! :)

**Comment by mikehaertl** [comment]
@nikazooz I've worked on a fix. Can you help testing, please? Simply use the latest `UrlManager.php` from master.

**Comment by nikazooz** [comment]
It works great! :)

**Comment by mikehaertl** [comment]
Ok. There's one restriction, though: If you configure a wildcard like `sr-*` in your `$languages` and send `/sr-latn/...` in the URL, `Yii::$app->language` will be set to `sr-LATN`. So you should avoid wildcard with that language.

I'll create another release including this fix. Thanks for reporting.
