### ISSUE TITLE
Rule on urlManager for have access to sitemap in subdomain

### ISSUE THREAD

**Issue by Global90** [codemix/yii2-localeurls#111]
i need ruls for access sitemap in subdomain.

my link for subdomain in

`http://client1.mymain.com`

sitemap file for client1 is on address:

`http://mymain.com/sitemap/client1/sitemap.xml`

i need rule for access on sitemap with this address:

`http://client1.mymain.com/sitemap.xml`

i use Yii2 and apache

Path App: public_html/app/config/web.php
Path Web: public_html/public_html/sitemap/client1/sitemap.xml

**Comment by mikehaertl** [comment]
I'm sorry, but I don't understand what exactly you want and how this is related to our extension here. If you think something is broken, please provide a clear example configuration, which URLs you are requesting, what you would expect and what you get instead.

**Comment by Global90** [comment]
i have blog service.
my sub blogs have sitemap file.

Example my Domain: **mymain.com**
Example blogs: **client1**

sitemap file is on this Address:
public_html/public_html/sitemap/**client1**/sitemap.xml

and now with this link you can download sitemap for **client1** : http://mymain.com/sitemap/client1/sitemap.xml

my problem:
i need load sitemap with this link for **client1**: http://*client1*.mymain.com/sitemap.xml

**Comment by mikehaertl** [comment]
What has this to do with the localeurls extension?

**Comment by Global90** [comment]
i use UrlManager Yii2.

**Comment by mikehaertl** [comment]
This extension is about URLs with a language code. For questions about the standard UrlManager, please consult the documentation or the yii2 support.
