### ISSUE TITLE
Image not shown when language changed

### ISSUE THREAD

**Issue by hdushku** [codemix/yii2-localeurls#112]
Thanks for the extension!
Works great.
But, I am facing with a problem, when I try the change the language the image url in upload folder does not show, but shown only for default language, en
The url:
http://link.com/uploads/Penguins.jpg - works ok in en
http://link.com/fr/fruploads/Penguins.jpg - does not work for other languages

**Comment by mikehaertl** [comment]
Sorry, I don't know what your `/upload` folder is and how you create that URL. If you don't want a language code in created Urls, just add `'language' => ''` to the route of your images. Like `Url::to(['some/route', 'language' => ''])` or `Html::a('Link', ['some/route', 'language' => ''])`.

**Comment by hdushku** [comment]
Thanks for you comment!
I tryed what you said but it gives me errors:
This is the code for the image
`<?php if($model->lead_photo) { ?>
        <a href="<?= Url::to(['/post/view', 'id' => $model->id]) ?>">
            <?= Html::img(Url::to(['/']) . $model->lead_photo, 
                ['class' => 'img-responsive center-block']
            ) ?>
        </a>
    <?php } ?>`

**Comment by mikehaertl** [comment]
Sorry, but again: I don't know anything about your image class and the internals of your code. And you didn't even use the code I showed you with `'language' => ''`. 

I can't see any problem on our side here and I can not help you debug your code, sorry.
