### ISSUE TITLE
How can set different Formatter config for each languages

### ISSUE THREAD

**Issue by msoa** [codemix/yii2-localeurls#114]
How can set different Formatter config for each languages?
Like this for each language:

```
        'formatter' => [
            'dateFormat' => 'dd.MM.yyyy',
            'decimalSeparator' => ',',
            'thousandSeparator' => ' ',
            'currencyCode' => 'EUR',
       ],
```

**Comment by mikehaertl** [comment]
Sorry, this is not a support forum but for reporting bugs to the library. Please check the yii support channels (forum, chat, ...) for questions like these.
