### ISSUE TITLE
Back to default language

### ISSUE THREAD

**Issue by DesRodman** [codemix/yii2-localeurls#117]
hello

Configure extension for DONT Language Detection in URL, like
'urlManager' => [
'enablePrettyUrl' => true,
'showScriptName' => false,
'class' => 'codemix\localeurls\UrlManager',
'languages' => ['en', 'ru', 'de'],
'enableLanguageDetection' => false,
'rules' => [
],
],

And i have a problem... Opening first time my main domain - everything OK... going to other languages - OK. But if i want to back to default language - i stay on previous... without any chance to go to default language.

I look in source and see that some problem with session in function "protected function processLocaleUrl($normalized)" in main ELSE

How can i fix it?

**Comment by mikehaertl** [comment]
Did you read this?
https://github.com/codemix/yii2-localeurls#reset-to-default-language

**Comment by DesRodman** [comment]
Thanks. Understood my mistake
