### ISSUE TITLE
Fallback to default language on unknown language in URL

### ISSUE THREAD

**Issue by mikehaertl** [codemix/yii2-localeurls#12]
Implement an option, so that an unknown language code in the URL doesn't give you a 404 but instead redirects to the default language.

Things to consider:

 * This will break URLs that look like a language code
 * Should we optionally include a country code? (`ll-cc`)

(There's also some discussion about this in #11 )

**Comment by mikehaertl** [comment]
@rolblo12 Maybe we can continue the discussion about this feature here.

I still wonder, why this would be useful. If you don't support a specific language, like say `fr` then why would someone use the URL `http://example.com/fr`? It would not be known to search engines, and you should of course also not use it in a language dropdown.

So the only case left, is, when a user modifies the URL and plays around with different languages. I don't think that we should catch this case.

**Comment by rolblo12** [comment]
The webapp does support a number of different languages, however, a user's browser might have *any* language variant in its accepted languages list. 
It is just essential to *avoid* a 404 error page on the user's *first* visit of the page. It is just catastrophic not to show the page to visitors from other countries or other accepted languages. They still might be able to read one of the supported languages.

To test this behavior I set the accepted languages to some language variants that I saw in the error 404 statistics of my web hosting.
Also to switch languages quickly without any special links in every page, I edit the URL of the browser.

**Comment by mikehaertl** [comment]
Ok, just ignore the language + country variants for now. We deal with them in #11. 

This here is only for the case, when a user hits the homepage with an invalid language. I still can't see, how this can ever happen. Maybe we continue discussion here after the issues in #11 are solved.

**Comment by rolblo12** [comment]
Hmm.. For me it is rather confusing to have several threads of discussion for the same module. 
I'll test a new version in the afternoon, got to fix some bugs in another project.

**Comment by mikehaertl** [comment]
Well, sorry about that :). But these *are* different issues and I want to keep things seperate. Otherwise we talk about many different problems with different solutions at once. So let's try to get the `xy-*` wildcard working first. Then we look what's still left to solve.

**Comment by mikehaertl** [comment]
> Edited browser URL to test.homewebtest.com/fr/site/contact -> Firefox shows the URL test.homewebtest.com/pt-pt/fr/site/contact, and the 404 error page. -> NOT OK It should just fall back to the default language

Please continue discussion here. So let me ask again: Why would a user ever use `/fr/site/contact` if you don't link to that language and don't promote that language? 

If the user manipulates the URL, it's perfectly fine that he gets a 404. You never claimed that `fr` is supported, so why should it fall back in this case?

**Comment by rolblo12** [comment]
Well, it is not really a 'hard' error, as it might appear in my comment. 
However, I'd rather avoid 404 error pages. I would have cut out anything that looks like a language code anyways and then checked if the found code were supported or not.
But it is up to you.

**Comment by mikehaertl** [comment]
You still did not answer my question: Why does a user use the wrong URL `/fr`?

**Comment by rolblo12** [comment]
Haha, because he is a tester..
No worries! I try to challenge a web application. Especially as you can edit the browser url easily.

So suppose you show personal data with an url `../user?id=15`.
I could just try to use `..?id=16` to get the personal data of someone else... 
So the webapp needs to check such security risks. 
You cannot argue, the user should not do that. 
Someone of the billions of users will do it eventually.

**Comment by mikehaertl** [comment]
Right, but that's out of the scope of this extension. If a user uses the app in a normal way. Inventing new URLs is not part of that. So I will not fix this - mostly because it's really not easy to find out if something is a valid URL or a invalid language code.
