### ISSUE TITLE
Secure cookies

### ISSUE THREAD

**Issue by robov** [codemix/yii2-localeurls#120]
How do I make the _language cookie secure like
```
                'secure' => true,   // cookie secure flag
                'httpOnly' => true,
````

**Comment by mikehaertl** [comment]
Did you notice the `languageCookieOptions` property?

https://github.com/codemix/yii2-localeurls/blob/master/UrlManager.php#L93

**Comment by robov** [comment]
Cool... I missed that
Can you include a code sniplet for the config of these options
This is also useful for other that have similar questiosn and start asking searching...

**Comment by mikehaertl** [comment]
To be honest I want to avoid making the README even longer. Explaining each and every secondary config option would be overkill and make it hard to read. I really want to focus on the main features. The option is already mentioned, though.
