### ISSUE TITLE
Add setlocale

### ISSUE THREAD

**Issue by flahol** [codemix/yii2-localeurls#122]
I think we should add gettext compatibility.

When the language is changed we should use the php function setlocale.
For example
if $language = 'en-US'

When we set 
`Yii::$app->language = $language;`

We could add 
`setlocale(LC_ALL, str_replace('-', '_', $language) . '.utf8');`

**Comment by mikehaertl** [comment]
I don't think, that this is in the scope of this extension. If at all, this should maybe happen in `setLanguage()` in the Yii core or something.
