### ISSUE TITLE
How to disable locales redirect and and at the same time to keep language parameter

### ISSUE THREAD

**Issue by v-lukoyanov** [codemix/yii2-localeurls#125]
My situation is similar on https://stackoverflow.com/questions/30568692/how-to-disable-locales-redirect-in-yii2-localeurls-for-specific-controller-modul, but after I add my controller to the 'ignoreLanguageUrlPatterns', there is a following:

When I open page with new language, for example **ru/s-m-account/profile**, the page is successfully translated to Russian. But when I want to going on another page of this controller (**s-m-account/index**), page is again refreshed into English. It is good that the redirect on RU does not occur and RU does not put out in a request. And it is necessary, but also it is necessary that RU remained and RU did not switch. 

So... I want that the system remembered language, but did not show it on controller **s-m-account**

I tried different options of settings and did not find the solution yet. My current choice:
```php
'urlManager' => [
            'class' => 'codemix\localeurls\UrlManager',
            'languages' => ['ru', 'en'],
            'enablePrettyUrl' => true,
            'showScriptName' => false,
            'enableStrictParsing' => true,
            'ignoreLanguageUrlPatterns' => [
                // route pattern => url pattern
                '#^s-m-account/#' => '#^s-m-account/#',
            ],
            'normalizer' => [
                'class' => 'yii\web\UrlNormalizer',
                'action' => \yii\web\UrlNormalizer::ACTION_REDIRECT_TEMPORARY, 
            ],
            'rules' => $urlRules,
        ],
```
Please, help with this question.

**Comment by mikehaertl** [comment]
I don't quite understand what you mean. Can you give a simple example:

1. Which URL did you open?
2. What happens?
3. What should happen instead?

**Comment by mikehaertl** [comment]
Closing this issue as there was no further feedback.
