### ISSUE TITLE
Merge LocaleUrl component into UrlManger

### ISSUE THREAD

**Issue by mikehaertl** [codemix/yii2-localeurls#13]
I'm not sure why I decided to create a separate `localeUrls` component. But I think, this is not really neccessary. We can combine everything into the `UrlManager` class.

While the configuration will become easier, this will als break backwards compatibility. It's thus scheduled for `1.1.0` release.

**Comment by rolblo12** [comment]
This sounds good. Then we have a component less to load.

**Comment by mikehaertl** [comment]
Cool. You can even already test it, if you want. It also contains the fixes from #11. The code is on this branch here: https://github.com/codemix/yii2-localeurls/tree/13-merge-localeurl-component

But note, that this is still work in progress. I'll first create a 1.0.5 release and then focus on the refactored (and BC breaking) 1.1.0 release.

**Comment by mikehaertl** [comment]
Done. So 1.1.0 is around the corner now.
