### ISSUE TITLE
Default language problem

### ISSUE THREAD

**Issue by ivan-ionut29** [codemix/yii2-localeurls#132]
In my config I set:

'language' => 'ro',
...........
'urlManager' => [
'class' => 'codemix\localeurls\UrlManager',
'languages' => ['ro', 'en'],
]

I want that my app to ignore browser default language, sessions and cookies ( for this language issue), so that the default language to be 'ro'.

**Comment by mikehaertl** [comment]
Sorry, this is not a support forum. Please check the README or the class source to find the available configuration options.
