### ISSUE TITLE
How to use anchor?

### ISSUE THREAD

**Issue by Sensetivity** [codemix/yii2-localeurls#134]
I have a problem with setting up an anchord.
I have next URL
http://photo-album.loc/ru#portfolio
http://photo-album.loc/uk#portfolio

I want to open a home page and set an anchord in selected language,
But instead I had redirected to http://photo-album.loc/#promotions
How it fix?
     
```
 'urlManager' => [
            'class' => 'codemix\localeurls\UrlManager',
            'enablePrettyUrl' => true,
            'showScriptName' => false,
            'enableLanguagePersistence' => false,
            'languages' => ['uk', 'ru'],
            'rules' => [
                '<_a:(login|logout|signup|confirm-email|password-reset-request|password-reset)>' => 'user/default/<_a>',
                '<_a:(home)>' => 'site/index',
                '<_a:(buy-photo-book|accessories)>' => 'site/<_a>',

                '<_m:[\w\-]+>/<_c:[\w\-]+>/<id:\d+>/<_a:[\w\-]+>/entity/<entity_id:\d+>/model_key/<model_key:[\w\-]+>' => '<_m>/<_c>/<_a>',
                '<_m:[\w\-]+>/<_c:[\w\-]+>/<_a:[\w\-]+>/entity/<entity_id:\d+>/model_key/<model_key:[\w\-]+>' => '<_m>/<_c>/<_a>',
                '<_m:[\w\-]+>/<_c:[\w\-]+>/<id:\d+>' => '<_m>/<_c>/view',
                '<_m:[\w\-]+>/<_c:[\w\-]+>/<id:\d+>/<_a:[\w\-]+>' => '<_m>/<_c>/<_a>',
                '<_m:[\w\-]+>' => '<_m>/default/index',
                '<_m:[\w\-]+>/<_a:(settings)>' => '<_m>/settings/default/index',
                '<_m:[\w\-]+>/<_c:[\w\-]+>' => '<_m>/<_c>/index',
            ],
        ],

```

**Comment by mikehaertl** [comment]
I'm sorry, but I don't understand your problem. Please describe clearly:

1. Which URL did you open?
2. What did you expect to happen?
3. What happened instead?

**Comment by Sensetivity** [comment]
1. I open http://photo-album.loc/ru#portfolio .
2. I expect to see page in russian language scrolled to #portfolio ancord.
3. I see a page http://photo-book.loc/#portfolio in ukrainian language that is default scrolled to #portfolio.

**Comment by mikehaertl** [comment]
What did you configure as default language in your app? I asume it's set to `ru`. Did you read this section: https://github.com/codemix/yii2-localeurls#default-language

So far I can not see any issue with this library. What you describe is the expected behavior.

**Comment by Sensetivity** [comment]
@mikehaertl Default language is Ukrainian (uk).
The lib skip language parameter when I use an ancord. 
I go to http://photo-album.loc/**ru**#portfolio but opened page is http://photo-album.loc/#portfolio without "ru" prefix.

**Comment by phpnode** [comment]
@Sensetivity the server never sees the `#` or anything after it so is unlikely to be related to the problem you're seeing.

**Comment by mikehaertl** [comment]
@Sensetivity As @phpnode says, the `#` is never sent to the server. So what happens if you open the URL without any anchor? Like http://photo-album.loc/ru ?

**Comment by Sensetivity** [comment]
@mikehaertl It open homepage on russian language.

**Comment by mikehaertl** [comment]
@Sensetivity I can not see how this could be possible. As said before: The URL sent to the server is always without the `#` part. It's the browser that will jump to the anchor position after receiving the page content from the server.

Maybe try to do some debugging with the web developer tools in your browser and inspect the requests being sent to the server and what is returned.

**Comment by mikehaertl** [comment]
@Sensetivity Any news here? Otherwhise I'd close this issue as I can not reproduce the problem.

**Comment by Sensetivity** [comment]
@mikehaertl Yep. You are rigth. It was problem with front-end part. Some JS script was modify an URL and it cause this issue. 
Nothing to do for you or your lib)
