### ISSUE TITLE
Internal component state

### ISSUE THREAD

**Issue by SamMousa** [codemix/yii2-localeurls#136]
In the most recent version of Codeception I've rewritten the Yii2 module making it more sensitive to state pollution after handling a request. The `UrlManager` component has a `protected $_processed` which means that it is unable to parse multiple requests.

This caused an issue with this component: https://github.com/Codeception/Codeception/issues/4920

I was wondering if it is really required to keep the `$_processed` state after the execution of `parseRequest`.

I'm assuming this variable is some kind of protection against infinite / unintended recursion.

I'm hoping it's possible to fix this in the `UrlManager`, if given some direction I can make a PR.

**Comment by mikehaertl** [comment]
> I was wondering if it is really required to keep the $_processed state after the execution of parseRequest.

This was added to fix #40. I don't want to remove this, to be honest. Can't you simply create a new instance of UrlManager for each test? In practical scenarios `parseRequest()` should only every be called once during a request lifecycle, as per the nature of of web apps, there's always only one request involved.

**Comment by SamMousa** [comment]
> "codeception/codeception": "2.4.x-dev",
    
That's one solution i'm considering, but it would require config since this is not needed or desired for every test. (Considering one might want to change component state in a test before a request)

I have looked at the issue and since it was an infinite loop I have 2 alternate solutions:
1. Surround the code in `parseRequest` with `try .. finally`, that way we can simply reset the value.
2. Replace the last line of `parseRequest` with this:
```php
$result = parent::parseRequest($request);
$this->_processed = false;
return $result;
```

> In practical scenarios parseRequest() should only every be called once during a request lifecycle, as per the nature of of web apps, there's always only one request involved.

While that is a valid point in most cases, there are exceptions. 

Given the fact that a fix is relatively easy and has low impact I'm hoping you'll change your mind!

**Comment by mikehaertl** [comment]
I think you misunderstood the problem. If I remember correctly #40 is about manually calling `Yii::$app->request->resolve()` **before** Yii processes the request. If you do this, then `parseRequest()` gets called twice during a request.

If you look at `processLocaleUrls()` (called from `parseRequest()`) you see, that we modify `pathInfo` to remove the language parameter from the URL. This must only happen **once** during a request otherwhise the second call would inspect the already modified `pathInfo` and make wrong conclusions about what to do next.

I can not see how your proposed changes would help here.

I know that "state is bad" and try to avoid it when possible. But it's not so easy in this case. I also think, that in OOP you'll find many components that keep some internal state. So if you write a generic test suite you have to deal with that situation. You can't expect that everyone modifies their code to become stateless just to adhere to the ideals of a test library.

**Comment by SamMousa** [comment]
> I think you misunderstood the problem. 
I think I did as well.

> make wrong conclusions about what to do next.
That makes the assumption that the request is actually the same altered request. Even then I'm not sure how that would lead to infinite recursion; I could imagine it just not working as expected though :)

> I know that "state is bad" and try to avoid it when possible. But it's not so easy in this case. I also think, that in OOP you'll find many components that keep some internal state. So if you write a generic test suite you have to deal with that situation. You can't expect that everyone modifies their code to become stateless just to adhere to the ideals of a test library.

That's right so I'll add the option to refresh components via configuration.
