### ISSUE TITLE
favicon.ico returns 404

### ISSUE THREAD

**Issue by turalus** [codemix/yii2-localeurls#137]
When browser requests /<language>/favicon.ico, website returns 404 page, in facet favicon.ico is there in /favicon.ico address.

How to fix this issue?

**Comment by mikehaertl** [comment]
Not sure if I understand. Does the `favicon.ico` file exist? If so the request should not be sent to Yii at all. And if it does not exist, the 404 ist correct.

It would be even better if you don't let requests for `*.ico` end up at your Yii application. You can change this in the webserver configuration.

**Comment by turalus** [comment]
Browser requests favicon.ico from domain.com/lang instead of domain.com. And obviously yii returns 404.

**Comment by mikehaertl** [comment]
Again: You should fix this in your webserver configuration. Any request for `*.ico` should never reach Yii. 

As there's nothing we can do to fix it here I'll close this issue.
