### ISSUE TITLE
Is it possible to keep main page without language parameter, but all other pages with?

### ISSUE THREAD

**Issue by turalus** [codemix/yii2-localeurls#138]
Currently my URLs look like:

...
domain.com/ru
domain.com/ru/page
domain.com/ru/other-page
...

What I need to do is, to remove language from url only in main page like this:

...
domain.com
domain.com/ru/page
domain.com/ru/other-page
...

Is it possible?

**Comment by mikehaertl** [comment]
No, you either always have a language code for all pages or not. You could only completely disable the language code for the default language. So in your case the `/ru` would be gone for all pages, if that's your default language. See the `enableDefaultLanguageUrlCode` option: https://github.com/codemix/yii2-localeurls#default-language

**Comment by turalus** [comment]
Okay, can you please at least give a point. Where to change script to get this behavior?

**Comment by mikehaertl** [comment]
Wait a second - I forgot the `ignoreLanguageUrlPatterns` option. You should play around with that:
https://github.com/codemix/yii2-localeurls#excluding-routes--urls

**Comment by anthonybachour** [comment]
Hello,

I am wanting to do the same exact thing.

I tried something like this:
'ignoreLanguageUrlPatterns' => [
                '#^/?#' => '#^/?#',
            ],

But it just disables language on all pages.

Is there a way to do it in rules maybe?

I am very new to Yii. If I do come up with a solution I'll update this comment.

**Comment by anthonybachour** [comment]
Hello Mike,

That seems to have worked! Thank you. I must have tried every variation but somehow skipped that one

**Comment by anthonybachour** [comment]
So the only issue now is that the user's language seems to be reset.

For example language is fr-ca then when link is clicked back to root language gets reset to en-ca.

Not sure if that is the intended function or not
