### ISSUE TITLE
yii baseUrl error

### ISSUE THREAD

**Issue by tiagocouto126** [codemix/yii2-localeurls#139]
When using:
baseUrl => '/'

The output url becomes //url
Using "your" dropdown widget. I believe it comes from your urlmanager concatenating '/' . 

I've made a workaround for urls not outputing /en/site/index

Probably the major problem here might be dropdown widget based on your code suggestion...

So feel free to mark as a "born dead" issue

Thank you for sharing this urlmanager

**Comment by mikehaertl** [comment]
I'd say the real major problem is that you should not configure `/` as `baseUrl`. :). Why would you want to do that?

**Comment by tiagocouto126** [comment]
I agree with you!
But this landed in my hands and I just shared the behavior with you to find if it was a bug or not.
I have managed and reconfigured and now it works with and without it.

**No error from your extension.**

Thank you.
