### ISSUE TITLE
Rename configuration options

### ISSUE THREAD

**Issue by mikehaertl** [codemix/yii2-localeurls#14]
With #13 all configuration options will be part of the `urlManager` component. We therefore should rename some of them so that it's clear that they are related to language options.

Suggested changes:

 * `enableDefaultSuffix` -> `useSuffixForDefaultLanguage`
 * `enablePersistence` -> `enableLanguagePersistence`

**Comment by rolblo12** [comment]
For me the new names are OK

**Comment by mikehaertl** [comment]
Changed my mind on the first option. It's now called `enableDefaultLanguageUrlCode`.
