### ISSUE TITLE
UrlManager, baseUrl

### ISSUE THREAD

**Issue by ivanchenkoandriy** [codemix/yii2-localeurls#141]
When I defined baseUrl as "http://mysite.localhost/" in the UrlManager configuration, I had that URLs:
- for the default language: http://mysite.localhost/mypage
- for another language: http://mysite.localhost/mypage/en
When baseUrl is empty or set to '/', then everything was fine.
To resolve the issue, remove the following lines:
```
if (strpos($url, '://')!==false) {
                     // Host URL ends at first '/' or '?' after the schema
                    if (($pos = strpos($url, '/', 8))!==false || ($pos = strpos($url, '?', 8))!==false) {
                        $insertPos += $pos;
                    } else {
                        $insertPos += strlen($url);
                  }
               }
```

**Comment by ivanchenkoandriy** [comment]
yiisoft/yii2                                  2.0.15.1

**Comment by mikehaertl** [comment]
Why did you define that baseUrl? That's not correct. The baseUrl is the relative path to your application in the web root not a full Url.

https://www.yiiframework.com/doc/api/2.0/yii-web-request#$baseUrl-detail

**Comment by ivanchenkoandriy** [comment]
Thank you. Sorry.

**Comment by ivanchenkoandriy** [comment]
My bad.
