### ISSUE TITLE
Using GeoIp as primary language detection method

### ISSUE THREAD

**Issue by westo27** [codemix/yii2-localeurls#156]
In the documentation it states: 
Since 1.7.0 language can also be detected via the webserver's GeoIP module. _Note though that this only happens if no valid language was found in the browser settings._

Is there any way to have GeoIp serve as the primary language detection method?

**Comment by mikehaertl** [comment]
No, because to me this would not make sense: The browser settings usually always tell us which language a user prefers. We should never have to override this with the Geo location of the user. Wouldn't you agree?

**Comment by westo27** [comment]
Thanks for the quick reply, I agree. I'll implement it that way.
