### ISSUE TITLE
index.php is shown in browser url

### ISSUE THREAD

**Issue by Shokhrukh2606** [codemix/yii2-localeurls#159]
When I use Url::to(['some/index']), it automatically generating index.php after host name

**Comment by mikehaertl** [comment]
You probably have not set `showScriptName` to `false`. https://www.yiiframework.com/doc/api/2.0/yii-web-urlmanager#$showScriptName-detail

But please understand that this is here is only for reporting bugs. If you think something is broken please provide a minimal example including config to reproduce the issue.
