### ISSUE TITLE
Get a 404 error page for url .../en/index.php

### ISSUE THREAD

**Issue by rolblo12** [codemix/yii2-localeurls#16]
Not sure how this was done. However, I saw this in the statistics of my web hosting.

It would be great if such an URL would lead to the *English index page* instead of the *404 error page* (in English).

**Comment by mikehaertl** [comment]
There were some issues with wrong URLs in 1.0.4 that should be fixed now. It could be, that the above URL was created because of that. But we can't do anything about the 404, because if the path to index.php is wrong, our app will not run at all.

Leaving this open to verify if the wrong URLs will be gone with 1.0.5.

**Comment by rolblo12** [comment]
I have verified this 404 error with your version I tested today (trunk)

**Comment by mikehaertl** [comment]
> I have verified this 404 error with your version I tested today (trunk)

But the 404 is OK, because the URL is wrong. I can't fix that. The question is rather: Are still wrong URLs created. I don't think so.

**Comment by rolblo12** [comment]
You are right, as you require that the UrlManager's 'enablePrettyUrl' must be true.
I am not sure what the original UrlManager does (having enablePrettyUrl=true) if it gets a non-pretty URL.

**Comment by mikehaertl** [comment]
I think, we can close this also. In 1.0.5 the whole URL matching and redirect logic has been rewritten and is now tested with all different combinations of `$showScriptName` and different `baseUrl`s. 

Feel free to report a new issue if it's still broken. Will release 1.0.5 very soon now.
