### ISSUE TITLE
Please fix this define

### ISSUE THREAD

**Issue by Mirocow** [codemix/yii2-localeurls#161]
https://github.com/codemix/yii2-localeurls/blob/master/UrlManager.php#L629

Must be
 
```php
if (defined(YII2_LOCALEURLS_TEST) && YII2_LOCALEURLS_TEST) {
```

**Comment by mikehaertl** [comment]
See https://github.com/codemix/yii2-localeurls/blob/master/UrlManager.php#L4

**Comment by mikehaertl** [comment]
@Mirocow As I see it there's nothing to fix. If you see erros or something please provide some details. For now I'm closing this.

**Comment by Mirocow** [comment]
Its my problem https://take.ms/m6hXMX
