### ISSUE TITLE
Url::to with rules

### ISSUE THREAD

**Issue by denostr** [codemix/yii2-localeurls#162]
Hi!

Is it possible to dynamic create url from rules?

For example:
```
'rules' => [
    'posts' => 'page/list-all',
]
```

`Url::to(['/posts', 'language' => 'ua']);`
Return `/ua` instead `/ua/posts`

**Comment by mikehaertl** [comment]
You must use the route in your call, not the pattern: `Url::to(['page/list-all', 'language' => 'ua'])
