### ISSUE TITLE
One language for all EU locales

### ISSUE THREAD

**Issue by overals** [codemix/yii2-localeurls#163]
Hi,

Is there a solution for the case if I need make redirect from all EU locales to "/en-eu"?

For example:
`'languages' => [
  'en-eu' => ['de', 'pl','fr','it'], /*and more EU countries*/
  'en',
],`

If there is no way, can it help to suggest something?

**Comment by mikehaertl** [comment]
Sorry, but we will not add this as a feature and to be honest it doesn't make much sense to me. Why would you give your user an URL like `/de/something` if such a page does not exist and instead you *always* redirect it to `/en-eu/something`? Then don't use the first URL at all. It would also be problematic to create such an URL.

If you really need something like this, you can solve it on the webserver level (Apache, Nginx, ...) and add rewrite rules there.
