### ISSUE TITLE
using Yii functionality

### ISSUE THREAD

**Issue by toir427** [codemix/yii2-localeurls#169]
https://github.com/codemix/yii2-localeurls/blob/933341668be705a71bf175ef51ce4ba7bac4b941/UrlManager.php#L445

Hello everone.
In my opinion we should be use the Yii functionality here

```
 Yii::$app->session->set($this->languageSessionKey, $language); 
```

**Comment by mikehaertl** [comment]
Can you explain? There was alread a PR for this (#168). But the way we access session properties already conforms to how Yii does it. See https://www.yiiframework.com/doc/guide/2.0/en/runtime-sessions-cookies#access-session-data.

Quote:

> To access the data stored in session, you can do the following:
>
> ```
> $session = Yii::$app->session;
>
> // get a session variable. The following usages are equivalent:
> $language = $session->get('language');
> $language = $session['language'];
> $language = isset($_SESSION['language']) ? $_SESSION['language'] : null;
> 
> // set a session variable. The following usages are equivalent:
> $session->set('language', 'en-US');
> $session['language'] = 'en-US';
> $_SESSION['language'] = 'en-US';
> ```

So why you think this should be changed?

**Comment by toir427** [comment]
Thanks for mentioning this information. Now, I know it
