### ISSUE TITLE
check for languages

### ISSUE THREAD

**Issue by schmunk42** [codemix/yii2-localeurls#17]
I noticed that, if I comment out languages, the `urlManager` starts behaving in weird way and creating wrong URLs, eg.

    http:/

instead of

    http://192.168.59.103:32772/de/

I am also running into endless redirects on some routes which should be the same, eg. `/` and `site/index` - one works, the other is an endless redirect.

I think there should be a check for the `languages` property, which should contain at least one element. And if not, throw a configuration exception.

What do you think?

**Comment by mikehaertl** [comment]
@schmunk42 Can you check if that commit fixes your problems? It should now bypass most features if no languages are configured.

**Comment by mikehaertl** [comment]
@schmunk42 Please check the new version 1.1.1. There was a severe redirect issue with default languages that was fixed here: https://github.com/codemix/yii2-localeurls/pull/18

**Comment by schmunk42** [comment]
LGTM now!
