### ISSUE TITLE
Bug in tests

### ISSUE THREAD

**Issue by machour** [codemix/yii2-localeurls#170]
Hi,

While running tests on my project, I noticed the following duplicated array keys in your RedirectTest file:

https://github.com/codemix/yii2-localeurls/blob/master/tests/RedirectTest.php#L232

https://github.com/codemix/yii2-localeurls/blob/master/tests/RedirectTest.php#L424

Both those entries gets overwritten 4 lines later:
```
      =>        '/site/page/?a=b' => '/en/site/page/?a=b',
                '/custom/?a=b' => '/en/custom/?a=b',
                '/noslash?a=b' => '/en/noslash?a=b',
      =>        '/site/page/?a=b' => [
                    ['/de/site/page/?a=b', 'request' => ['acceptableLanguages' => ['de']]],
                ],
```

**Comment by mikehaertl** [comment]
Fixed, thanks.
