### ISSUE TITLE
Help me please. Error with route.

### ISSUE THREAD

**Issue by T3R3AND** [codemix/yii2-localeurls#176]
I created my component and sent a route to it.
`			'rules' => [
				'' => 'site/index',
				['class' => 'app\components\UrlManager'],
			],`
			
**app\components\UrlManager**
[https://pastebin.com/2RG14ErC](https://pastebin.com/2RG14ErC)

The error is as follows: What if I, for example, follow the direct link "local.host/url-personal-link", then redirect to "local.host/en/site/error".

How do I redirect to "local.host/{language}/url-personal-link"?

**Comment by mikehaertl** [comment]
I'm sorry, but I can not make much sense of your code. It doesn't even use our library at all. 

Please understand that we can't provide any help on how to use the plugin. It requires at least a minimum understanding of how things interact in Yii2. I recommend you study the manual on url routing first and also read our README.

**Comment by T3R3AND** [comment]
> I'm sorry, but I can not make much sense of your code. It doesn't even use our library at all.
> 
> Please understand that we can't provide any help on how to use the plugin. It requires at least a minimum understanding of how things interact in Yii2. I recommend you study the manual on url routing first and also read our README.

**Full UrlManager:**
[https://pastebin.com/XENu6puC](https://pastebin.com/XENu6puC)

I would like to ask if you could help me somehow fix this redirect.

**Comment by mikehaertl** [comment]
Sorry, but this is not a support forum. And your code still looks like you're missing some basic concepts. For example:

```
'rules' => [
                '' => 'site/index',
                ['class' => 'app\components\UrlManager'],
            ],
```

You can not put a UrlManger here.

Again: Please understand, that we can not provide project specific help.
