### ISSUE TITLE
Redirect for specific languages

### ISSUE THREAD

**Issue by AndriiTereshchuk** [codemix/yii2-localeurls#183]
Greetings, please tell me there are countries like Belarus and Kazakhstan and Russia. I have the following locales enabled: 'languages' => ['en', 'ru', 'uk'], when I set the most priority Belarusian language in the browser, I want to be redirected to 'ru', is it possible to do this?

**Comment by mikehaertl** [comment]
Please understand that this is not a support forum, so we can not guide you how to set up everything. In your case you need to configure a language *and* a region, like `ru-RU` or something. 

See here: https://www.yiiframework.com/doc/guide/2.0/en/tutorial-i18n#locale

But it seems that `ru` has no support for regions in yii2 so far. But that's a question for yii2 itself, not our extension here:
https://github.com/yiisoft/yii2/tree/master/framework/messages
