### ISSUE TITLE
Logout from Yii2 advanced template cause redirect loop

### ISSUE THREAD

**Issue by mehrna** [codemix/yii2-localeurls#19]
First of all TNX for your great extention!

I'm using advanced template for my project and I run into a problem with your extention.

Everything works fine except when user logout. logout will redirect to home url with the default language at the end (like this: http://example.com/fa), but it has a redirect loop and home page will never shown till user delete the default language from address bar(like this: http://example.com).

Also "enableDefaultLanguageUrlCode" has its default value(I mean it is false).

What am I doing Wrong? Or maybe its an issue?

**Comment by mikehaertl** [comment]
Which version are you using? There was a problem with 1.1.0. The 1.1.1 release should fix many problems.

**Comment by mehrna** [comment]
I'm using 1.1.0 right now.. I will update it to latest version and give you feedback!

**Comment by mehrna** [comment]
You were right!

Upgrading from version 1.1.0 to 1.1.1 solved the problem! Thanks a lot.
