### ISSUE TITLE
Problem with login in different languages

### ISSUE THREAD

**Issue by mehrna** [codemix/yii2-localeurls#20]
I'm Using ActiveForm to generate login form on index view of a controller. Like this:

    $form = ActiveForm::begin(
        [
            'id' => 'login-form',
            'method' => 'post',
            'action' => 'site/login'
        ]
    );

everything is okay when you submit form on default language using `'enableDefaultLanguageUrlCode' => false`,

but changing to `'enableDefaultLanguageUrlCode' => true` or using other languages for loging in cause 404 error.

One way for login correctly in all languages is to use `'enableDefaultLanguageUrlCode' => false` and get the language code, then if it isn't the default one, pass it in form's action, but I think this is not nice!
then what is you suggestion?

**Comment by mikehaertl** [comment]
You should use array format for your form action: `['site/login']`.

**Comment by mehrna** [comment]
Right!

Using array format solved the problem. TNX @mikehaertl.

**Comment by mikehaertl** [comment]
Good. You should get used to always using array format, whenever Yii expects a url somewhere (and you link to a page on your site). Otherwhise you bypass Yii's built in method for URL creation.

**Comment by mehrna** [comment]
OK, got it. Thank you for your help!
