### ISSUE TITLE
index page redirect

### ISSUE THREAD

**Issue by dataskills** [codemix/yii2-localeurls#24]
Everything works as expected but there is a case that google analytics claims is hurting my seo. 

I have  enableDefaultLanguageUrlCode enabled, as it should be, but google frowns upon a redirect from the index page of a website so http://site.com makes a 302 redirect to http://site.com/defaut-language
For this case, there would ideally be no redirect for the index page url.

I can't see a way to handle this case with any features in the package, I was wondering if you have a suggestion on how to handle this case. I realize that perhaps this is not meant to be in the scope of the functionality.

I would appreciate a suggestion if you have one. I appreciate your work on this package, it has been a great help to me.

**Comment by mikehaertl** [comment]
Why don't you set `enableDefaultLanguageUrlCode` to `false`?

**Comment by dataskills** [comment]
Correct me if I am wrong but that would make it so that the default
language code is not in the url; I need the language in the url, if I stop
showing the language in the url for my default language I would be changing
the url for tens of thousands of pages. This would be a much worse google
seo problem than the index page redirect issue I am facing now. I have had
the language in the url for many years, I just moved the site to the yii2
platform and decided to use localeurls. We support 14 languages and
everything is great except for this one issue.

On Wed, May 27, 2015 at 12:14 AM, Michael Härtl <notifications@github.com>
wrote:

> Why don't you set enableDefaultLanguageUrlCode to false?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/codemix/yii2-localeurls/issues/24#issuecomment-105789305>
> .
>



-- 
------------------------
J. Bundy
dataskills@gmail.com
+1.206.406.1534

**Comment by phpnode** [comment]
@dataskills to clarify are you saying that you want `http://example.com/` to show the same content as `http://example.com/en`, but further links should be to `http://example.com/en/some/page.html` ?

**Comment by dataskills** [comment]
I think the short answer to your questions is yes but I would put it a
different way; I am simply saying that according to google analytics there
should not be any redirects from the index page of a website. I don't
necessarily like or dislike this but since google is holding the all the
cards I have to try to do it their way. So, again, it is more about not
redirecting from the index page rather than what will show on any
particular subsequent page.

On Wed, May 27, 2015 at 2:28 PM, Charles Pick <notifications@github.com>
wrote:

> @dataskills <https://github.com/dataskills> to clarify are you saying
> that you want http://example.com/ to show the same content as
> http://example.com/en, but further links should be to
> http://example.com/en/some/page.html ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/codemix/yii2-localeurls/issues/24#issuecomment-106084908>
> .
>



-- 
------------------------
J. Bundy
dataskills@gmail.com
+1.206.406.1534

**Comment by mikehaertl** [comment]
@dataskills Well, that's exactly what the `enableDefaultLanguageUrlCode` is for: If you want to have the default language under `http://www.example.com` (and redirect requests from `/en` to `/`) then leave it as `false`.

And if you want to have `http://www.example.com/en` for your default language instead (and redirect from `/` to `/en`) you should set it `true`.

But you can't have both, as this would be duplicate content and that's much worse from a SEO perspective.

**Comment by dataskills** [comment]
You can have both, you just make one of the urls canonical which is what I
shall do. I will just make a rewrite rule that will serve the canonical
version which will supersede yii routing for that one case. I appreciate
your consideration on this matter, have a great day.

On Thu, May 28, 2015 at 1:19 AM, Michael Härtl <notifications@github.com>
wrote:

> @dataskills <https://github.com/dataskills> Well, that's exactly what the
> enableDefaultLanguageUrlCode is for: If you want to have the default
> language under http://www.example.com (and redirect requests from /en to /)
> then leave it as false.
>
> And if you want to have http://www.example.com/en for your default
> language instead (and redirect from / to /en) you should set it true.
>
> But you can't have both, as this would be duplicate content and that's
> much worse from a SEO perspective.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/codemix/yii2-localeurls/issues/24#issuecomment-106226561>
> .
>



-- 
------------------------
J. Bundy
dataskills@gmail.com
+1.206.406.1534

**Comment by mikehaertl** [comment]
I see your point now. I wonder, if we should take care for this in the extension somehow. Not really sure yet, how it should work, though.

If you have suggestions, let me know. I'll leave this open for discussion.

**Comment by dataskills** [comment]
I'm not 100% sure either, I think we will find out whether this is an issue
for others. Again, thank you for your consideration. If I come upon a
specific suggestion I will post it.

On Fri, May 29, 2015 at 12:59 AM, Michael Härtl <notifications@github.com>
wrote:

> I see your point now. I wonder, if we should take care for this in the
> extension somehow. Not really sure yet, how it should work, though.
>
> If you have suggestions, let me know. I'll leave this open for discussion.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/codemix/yii2-localeurls/issues/24#issuecomment-106735602>
> .
>



-- 
------------------------
J. Bundy
dataskills@gmail.com
+1.206.406.1534

**Comment by yoyhosoft** [comment]
Hi,
I set app language to
    'language' => 'th'
and
    'urlManager' => [
            'class' => 'codemix\localeurls\UrlManager',
            'languages' => ['en-US','en','th'],
        ]

then, open new browser in private mode (or clear cookie) and open my site,  
url still redirect to /en-US, instead of /th

it means, can't set default language via app language parameter?

**Comment by mikehaertl** [comment]
@yoyhosoft Please open a new issue. Your problem is not related to the issue discussed here.

**Comment by vc7deo** [comment]
please see my settings

i need to hide **en** from the url,that is if my default language is English  i don't want to show **en** in the url
     
i tried enableDefaultLanguageUrlCode to be true and false

but nothing affect my url
http://localhost/multi/backend/web/en/site/login

   'urlManager' => [
            'class' => 'codemix\localeurls\UrlManager',
            'languages' => ['en', 'ar'],
            //'enableLocaleUrls' => true,
            'enableDefaultLanguageUrlCode' => false,
            'enablePrettyUrl' => true,
            'showScriptName' => false,
            'rules' => [
            ],
        ],

**Comment by vc7deo** [comment]
sorry i didnt set the language in the main.php

    'language' => 'en',
    'sourceLanguage' => 'en',

now its working

**Comment by xr0m3oz** [comment]
"codemix/yii2-localeurls": "^1.4",

```
		'urlManager' => [
			'class' => 'codemix\localeurls\UrlManager',
			'suffix' => '/',
			'normalizer' => [
				'class' => 'yii\web\UrlNormalizer',
				// use temporary redirection instead of permanent for debugging
				'action' => \yii\web\UrlNormalizer::ACTION_REDIRECT_PERMANENT,
			],
			'languages' => ['en','ru','uk'],
			'enablePrettyUrl' => true,
			'showScriptName' => false,
			'rules' => [
			],
		],
```
All pages work correctly only when you enter an address site.com/en   (no redirect to site.com/en/ )
If you remove the suffix from the settings that also does not work for some reason the redirect. site.com/en/   (no redirect to site.com/en )

**Comment by mikehaertl** [comment]
Closing this issue for now. If someone feels like we really need to address this, feel free to leave a comment and we may reopen the issue.

@xr0m3oz Please open a new issue as your problem is probably not related to the discussion here. It would help if you could clearly describe: What did you do? What did you expect? What happened instead?

**Comment by w3lifer** [comment]
https://support.google.com/webmasters/answer/189077
