### ISSUE TITLE
How to disable locales redirect in yii2-localeurls for specific controller/module

### ISSUE THREAD

**Issue by linslin** [codemix/yii2-localeurls#25]
While opening a Question on Stackoverflow..., this question maybe can be answered here.

http://stackoverflow.com/questions/30568692/how-to-disable-locales-redirect-in-yii2-localeurls-for-specific-controller-modul

**Comment by mikehaertl** [comment]
I see your point but this is not supported (yet). URL parsing happens after localeurls has done its job. So the extension has no information about the current controller or module as this is decided later on. 

I'm unsure how we could implement this. We could maybe add some regular expression URL patterns that if matched during parsing will skip language processing. And also a list of route patterns, where language should be ignored when building a URL.

**Comment by linslin** [comment]
Thanks for your reply. So, this is not a edge case I promise. Currently I taking a look on your codes. Its seem not that complicated to define exclude url patterns. 

While this extension is executed before a controller/module was initialized its the best way to define exclude routes. Do you agree to that?

**Comment by linslin** [comment]
What about: 

```
        'urlManager' => [
            'class' => 'codemix\localeurls\UrlManager',
            'languages' => [
                'en' => 'en-gb',
                'de' => 'de-de'
            ],
            'enableLanguageDetection' => false,
            'enablePrettyUrl' => true,
            'showScriptName' => false,
            'rules' => [

            ],
            'filter' => [
                'api/',
                'test/'
            ]
        ],
```

And in `protected function processLocaleUrl($request)` line 189+
```
        //filter routes
        foreach ($this->filter as $filter) {
            if (preg_match("#^($filter)\b(/?)#i", $pathInfo)) {
                return true; //proceed with application
            }
        }
```

**Comment by mikehaertl** [comment]
Yeah, something like this. But you also need something for URL creation. So we need to specify a list of routes or - even better - another regular expression pattern that matches many routes (otherwhise you'd have to manually specify all action routes available e.g. from a module).

**Comment by linslin** [comment]
Yep, agree to this. For this moment, static pattern would be enough. Do you agree?

**Comment by mikehaertl** [comment]
@linslin Can you check if my implementation in this branch here works for you?
https://github.com/codemix/yii2-localeurls/tree/25-ignore-patterns

**Comment by mikehaertl** [comment]
@linslin Any news here? Did you get a chance to try the new implementation?

**Comment by linslin** [comment]
Hey @mikehaertl sorry for this late answer. The new feature works pretty nice. Thanks so far!

**Comment by mikehaertl** [comment]
Great. I'll prepare a 1.2.0 release with this new feature then.

**Comment by linslin** [comment]
:+1:
