### ISSUE TITLE
enableDefaultLanguageUrlCode disables Yii Debug Toolbar

### ISSUE THREAD

**Issue by waterloomatt** [codemix/yii2-localeurls#27]
Haven't done too much digging but setting 'enableDefaultLanguageUrlCode' => true hides the Yii Debug Toolbar from view. Removing this setting restores it.

Yii Version       2.0.4
Environment   dev
Debug Mode   Yes
PHP Version   5.6.8
Xdebug           Enabled
APC                Enabled
Memcache      Disabled

**Comment by waterloomatt** [comment]
Turns out to be a simple URL rule issue and not this extension's fault at all. This ticket can be closed.

**Comment by rahulk-k** [comment]
I also have the same issue.

**Comment by mikehaertl** [comment]
@rahulk-k Your issue should be fixed in release 1.1.2. Also see #32.

**Comment by rahulk-k** [comment]
@mikehaertl , Thanks for your quick fix.
