### ISSUE TITLE
Example Language Selection Widget contains some issues

### ISSUE THREAD

**Issue by julien101** [codemix/yii2-localeurls#28]
Your example is great for building custom code. Only some issues avoid it to run fine:
- line 19: 
Yii::$app->localeUrls->languages
should be: Yii::$app->urlManager->languages
- line 25 & 29: $isWildCard
 should be: $isWildcard

**Comment by mikehaertl** [comment]
Thanks! I've actually never used the code. Just wanted to show the basic idea. It's fixed now and hopefully works.
