### ISSUE TITLE
different controller/action names for different languages

### ISSUE THREAD

**Issue by sajtosnorbert** [codemix/yii2-localeurls#29]
Hi!

Is it possible to create different controller/action names (or lets call them aliases) for different languages that point to the same action?

For example:
/en/contact -> site/contact
/de/kontakt -> site/contact
etc.

So that If the language is 'de' then Url::to(['site/contact']) will return '/de/kontakt'.

Thanks,
Norbert.

**Comment by mikehaertl** [comment]
No, that's not supported by this extension, sorry. It only deals with language codes in the URL, not with translation. I would probably use a custom URL rule to achieve what you want. If you keep things configurable and generic, this could be a nice candidate for another simple extension ;).
