### ISSUE TITLE
Language change automatically.

### ISSUE THREAD

**Issue by invaderhd** [codemix/yii2-localeurls#30]
Hello I have 2 languages on my website pt-PT and en. Portuguese is the default language. In general everything works perfect.

But in the few days during my tests I change the language a lot and sometimes I change from pt-PT to en then change back to pt-PT and it change but if I wait a few seconds and try to open a page it goes back do en. 

When this bug appears I have to logout, restart the browser and then it return to normal behaviour. 
Do you have any idea what can cause this strange behaviour?

**Comment by mikehaertl** [comment]
Hmm, I don't really have an idea. What is your configuration? And do you use [persistence](https://github.com/codemix/yii2-localeurls#persistence)?

It would definitely help, of course, if you could reproduce this somehow.

**Comment by invaderhd** [comment]
yes this is my main problem I can't reproduce it. It happens sometimes.

I use this settings:
```
'urlManager' => [
            'class' => 'codemix\localeurls\UrlManager',
            'languages' => [ 'pt-PT', 'en'],
            'enableLanguageDetection' => false,
            'enableLanguagePersistence' => true,
        ],
```

**Comment by mikehaertl** [comment]
Could it be that this only happens, after the session times out? But you mentioned above, that you have to logout - so the session seems to still be alive.

Any further input would really help.

**Comment by mikehaertl** [comment]
@invaderhd Could you please also describe, how exactly you change the language each time? Maybe you can give a list of URLs that you use and what happens for each of them (redirect, showing page in specific language, etc). I just want to have a complete picture of the issue.

**Comment by invaderhd** [comment]
Sorry for the delay in this response.

The problem appear again, this is really strange. My main language is pt-PT usually everything works fine, but sometimes the problem appear and only disappear is I close the browser am erase cookies and everything.

When this problem appear, this is what happened:
1 - Website in english (www.domain.com/en) 
2 - Change to pt (www.domain.com/pt-PT -> www.domain.com) this works and the website appear in pt
3 - I do a refresh 3 or 4 seconds after change to pt and it refreshes and keep in portuguese
4 - I wait 10-20 seconds or more and do a refresh and the website redirect do English

This is really strange there are any procedure to debug this problem?

**Comment by mikehaertl** [comment]
Well, the code is pretty straightforward. In your case I would probably add some `Yii::trace()` calls starting from this line here: 

https://github.com/codemix/yii2-localeurls/blob/master/UrlManager.php#L231

This is active, when no language code was found in the URL. Now the extension tries several things to find out, if it has to redirect. It first checks session (L232), then browser languages (L238) and finally default language(L247ff).

So if you add a `Yii::trace()` call to every possible condition, it should hopefully give you a clue what goes wrong.

**Comment by invaderhd** [comment]
Thank you for your help. The error is not related with the plugin, to be more specific this isn't an error at all.

I have a background ajax call to check for new messages (every 30s), and during development I have multiple tabs opened sometimes I have the website in english then change in one tab to portuguese, but the ajax call from the tab that still not refreshed and that is in english send the request with the url in english and this cause my strange problem.
Sorry for you spend time answer me when everything works perfect.
