### ISSUE TITLE
Any POST request without language parameter 302 redirects page

### ISSUE THREAD

**Issue by turalsprofile** [codemix/yii2-localeurls#31]
For example when I send form data into

```
/controller/action
```

rather than

```
/en/controller/action
```

It 302 redirects form.

Is there any fix for that?

**Comment by mikehaertl** [comment]
How do you create your form tag? When the user sees the form, the language is usually already negotiated. So the form will submit to the full URL that already includes the language code. I wonder, why you have the wrong URL in your form action.

**Comment by dataskills** [comment]
I recently had a similar problem when sending an ajax request. It took me a
very long time to realize I had to add the language param to the url
parameter to avoid getting 400 Bad Request. I'm not sure that can be
avoided though, maybe just add a note about it in the docs?

On Tue, Jun 23, 2015 at 12:25 AM, Michael Härtl <notifications@github.com>
wrote:

> How do you create your form tag? When the user sees the form, the language
> is usually already negotiated. So the form will submit to the full URL that
> already includes the language code. I wonder, why you have the wrong URL in
> your form action.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/codemix/yii2-localeurls/issues/31#issuecomment-114389516>
> .
>



-- 
------------------------
J. Bundy
dataskills@gmail.com
+1.206.406.1534

**Comment by mikehaertl** [comment]
As there was no more feedback about this issue and I consider this to be a problem of wrong use I'll close this issue for now. If someone wants to reopen, please provide simplified example code to reproduce the issue.
