### ISSUE TITLE
Yii Debugger problem

### ISSUE THREAD

**Issue by harrytang** [codemix/yii2-localeurls#32]
when enableDefaultLanguageUrlCode set to true, the Yii Debugger disappear.

**Comment by mikehaertl** [comment]
Had no time yet to verify this issue, but do you see any errors in the browser's console or in the network tab? Any hint what goes wrong?

**Comment by harrytang** [comment]
may be case-sensitive problem.
- if I set 'languages' => ['vi-VN'], it's not work (the Yii Debugger URL is  /vi-VN and it will be redirected to vi-vn).
- it work find if I set 'languages' => ['vi-vn']

**Comment by mikehaertl** [comment]
Ok, maybe we have an issue here. Could you please give some more details:

 * What is the code that you use to create the URL for the page where the problem happens?
 * What URL is being created by that code?

**Comment by mikehaertl** [comment]
The above change should fix your issue. Can you help testing it, please?

**Comment by harrytang** [comment]
it's work fine now. Thanks for your quick fix.

**Comment by mikehaertl** [comment]
Glad to hear that. I've just released 1.1.2 with this fix included. Thanks for your help!
