### ISSUE TITLE
Not found page has wrong urls

### ISSUE THREAD

**Issue by laziz-karimov** [codemix/yii2-localeurls#33]
I have a page with url
something.com/en/controller/method?id=12
and this page does not exist.

Generated links are:
something.com/ru/site/error?id=12
something.com/de/site/error?id=12
something.com/fr/site/error?id=12

But I need
something.com/ru/controller/method?id=12
something.com/de/controller/method?id=12
something.com/fr/controller/method?id=12

Any ideas? Thanks a lot in advance

**Comment by laziz-karimov** [comment]
Sorry, I've read closed issues, and found the answer

**Comment by laziz-karimov** [comment]
As I understood correctly, this issue was a bug in previous versions? I guess I am missing something, only 404 pages are having wrong language urls...

**Comment by mikehaertl** [comment]
Could you add some simple example code to reproduce? It should especially show how and where you create the links.

**Comment by mikehaertl** [comment]
I think, I see now. You've used the example language selection widget, right? Se offending line is probably this:

```
$route = '/'.Yii::$app->controller->route;
```

When Yii encouters an error, it runs the configured [errorAction](http://www.yiiframework.com/doc-2.0/yii-web-errorhandler.html#$errorAction-detail) internally. This seems to change the current controller's route. I'm not sure yet, how to fix this.

**Comment by mikehaertl** [comment]
It's not so easy to solve this in a solid way. When a visitor used an invalid URL that leads to a 404, it could be, that the URL could not be resolved to a valid route. But the current route is required by the language selector, to create a different language URL for the current page.

I think, the only valid workaround is not to show the language dropdown on the error page. I now, that's not perfect, but I can't think of a better solution - at least not a simple one.

**Comment by mikehaertl** [comment]
@laziz-karimov I've added error handling to the example. Can you try, if this works for you?

https://github.com/codemix/yii2-localeurls/commit/1b308f9a79417642a94ed1dadbd0de362b1ec80d

**Comment by laziz-karimov** [comment]
Thanks a lot for response. It is working now.

Small mistypes in your edited example:
not $this->_isError = $route === Yii::$app->errroHandler->errorAction;
but $this->_isError = Yii::$app->controller->route === Yii::$app->errorHandler->errorAction;

**Comment by mikehaertl** [comment]
Ok, thanks. Fixed the example.

**Comment by laziz-karimov** [comment]
Small mistype in Yii::$app->errroHandler->errorAction

**Comment by mikehaertl** [comment]
Fixed, thanks.
