### ISSUE TITLE
absolute url problem

### ISSUE THREAD

**Issue by TheSaturn** [codemix/yii2-localeurls#34]
Hi! I have problems with url creating with controller and subdomain
I have this config: 
```
'urlManager' => [
            'class' => 'codemix\localeurls\UrlManager',
            'enablePrettyUrl' => true,
            'showScriptName' => false,
            'enableDefaultLanguageUrlCode' => true,

            // List all supported languages here
            // Make sure, you include your app's default language.
            'languages' => [ 'en',  'ar'],
            'rules' => [
                'http://account.test.ru/<ev:(.*)>/' => 'account/<ev>',
            ]
        ],
```
and when I try to create absolute link:
```

    <?= $resetLink = Yii::$app->urlManager->createAbsoluteUrl(['/account/reset-password', 'token' => 'ssss']);?>
```
I get:  /arhttp://account.test.ru/reset-password?token=ssss
The problem exists because parent::createUrl($params); at 148 UrlManager.php returns 'http://account...' which  gets through $value => $key  in $rules array. And then "/$language$url" at 162 string
So I "fix" it  with:
```
            'rules' => [
                'account/<ev>' => 'account/<ev>',
                'http://account.test.ru/<ev:(.*)>/' => 'account/<ev>',
            ]
```

**Comment by mikehaertl** [comment]
This is nasty. The documentation to `yii\web\UrlManager::createUrl` states, that:

> The URL created is a relative one. Use [[createAbsoluteUrl()]] to create an absolute URL.

Which is obviously not the full truth. If you use a URL rule with a server name, it returns an absolute URL. I don't have an idea yet, how to fix this.

**Comment by mikehaertl** [comment]
I wonder, if this proposed feature would help you: https://github.com/codemix/yii2-localeurls/commit/834d20b721db12ef1bbaea336e5616d17eb7a06d. Maybe you want to give it a try? You should be able to exclude some routes / URLs from language parsing.

**Comment by phpnode** [comment]
ping @TheSaturn were you able to work around the issue using `ignoreLanguageUrlPatterns`?

**Comment by mikehaertl** [comment]
@TheSaturn I'm closing this for now, because apart from the above workaround I can't think of a better workaround.

If you still feel we should find a better fix or can come up with something feel free to reopen.
