### ISSUE TITLE
How to force https

### ISSUE THREAD

**Issue by invaderhd** [codemix/yii2-localeurls#36]
My website should run entirely in https, it's running on a facebook canvas page that required that every with ssl.

But i'm keeping have a problem if I change from secondary language to primary language I get an request without https and this break my website inside facebook canvas page.

Get a look in my network log:
![http redirect https language](https://cloud.githubusercontent.com/assets/1872297/8698617/85aca04c-2af7-11e5-86f6-a56435f82070.png)

As you see it call the default language https://domain.com/pt-pt/site (pt-pt is the default language), then is redirected (302) to http://domain.com/site/index (in the image the "popup" with the http url is from the second entry) then this url without the https hit my htaccess than redirect it back to https, but on facebook the website is blocked before this happen because every request must be with ssl.

There is an way to force the use of https every time?

**Comment by mikehaertl** [comment]
Hmm, currently not at my dev computer, so I can't test. Can you maybe help debug the issue? I can't really see, why it should change the schema. The redirect in this case is probably triggered here:

https://github.com/codemix/yii2-localeurls/blob/master/UrlManager.php#L266

The redirect then happens in `redirectToLanguage()`. Maybe you can check the `$redirectUrl` there. Usually this should be  a relative URL which is then passed to [Response::redirect()](http://www.yiiframework.com/doc-2.0/yii-web-response.html#redirect()-detail). Could it be that this Yii2 method somehow creates a URL with the wrong schema?

**Comment by invaderhd** [comment]
Thank you for your quick answer. I debug some request and seems that the problem is with Response::redirect().

In any controller if I add something like this:
Yii::$app->getResponse()->redirect('/site/index');

It always redirect to a http request instead of keeping the https.

**Comment by mikehaertl** [comment]
For reference, the related Yii issue is https://github.com/yiisoft/yii2/issues/9116

**Comment by invaderhd** [comment]
Solved thank you mikahaertl you are the one that help me found the problem.

**Comment by mikehaertl** [comment]
Closing this as it was caused by a reverse proxy setup with nginx. If you add the right headers in your nginx configuration the problem should be gone.
