### ISSUE TITLE
Cookie value

### ISSUE THREAD

**Issue by ustmaestro** [codemix/yii2-localeurls#38]
I found a bug in `protected function processLocaleUrl($request)`.

Function `$this->matchCode($language)` expects `$language` as `string` but `$language = $request->getCookies()->get($this->languageCookieName);` is an `object`

Changes:

Line 273: 
 
		$language = $request->getCookies()->get($this->languageCookieName);

to 
 
		$cookie = $request->getCookies()->get($this->languageCookieName);
		if($cookie){
			$language = $cookie->value;
		}

**Comment by phpnode** [comment]
@ustmaestro I think the line should actually be:
```php
$language = $request->getCookies()->getValue($this->languageCookieName);
```

please would you mind opening a PR?

**Comment by mikehaertl** [comment]
@ustmaestro Thanks for the report. I think @phpnode's suggestion should work. I'm just not sure, why the current test cases don't fail. They actually (shoul) also test the cookie feature. Will have to take a close look later.

If a PR is too much work for you, don't worry. I can also take care of this.

**Comment by mikehaertl** [comment]
@ustmaestro I've fixed this now. It's interesting to note though, that the bug had no effect. `yii\web\Cookie` implements a `__toString()` method. In `matchCode($code)`, `$code` is used in two places:

```
$parts = explode('-', $code);
in_array($code, $this->languages);
```

I would have expected the cast to `string` in `explode()` - but not really for `in_array()`. Still it worked, even without my fix. 

Anyhow, it's fixed now. Thanks again.

**Comment by ustmaestro** [comment]
bool in_array ( mixed $needle , array $haystack [, bool $strict = FALSE ] )

As you can see `$needle` is `mixed` and it can be an `array` (object) that's why your test is not throwing any error

In my case I changed the languages array like

	'languages' = > [
		'en' => 'English',
		'ro' => 'Română',
		'ru' => 'Русский',
		....
	]


and changed `in_array` with `array_key_exists` that's how I found this bug.

I changed the languages array because of using https://github.com/OmgDef/yii2-multilingual-behavior in my application

**Comment by mikehaertl** [comment]
@ustmaestro Can you confirm that my change above fixes the problem? If everything is fine I'll create a new release.

**Comment by ustmaestro** [comment]
Yes, it fine now.

Different controller/action names for different languages
https://github.com/codemix/yii2-localeurls/issues/29

Have you planned to do this extension, that will be a great yii2 extension for multilingual websites
I and think many other users is need for this extension 

Also it can be a great feature to add dinamic links
Example:

 site.com/en/blog/post/sample-post
 site.com/ro/blog/post/post-simplu
 site.com/ru/blog/post/prostoi-post

This is the same post but in different languages with slug stored in db

**Comment by mikehaertl** [comment]
> Have you planned to do this extension

Sorry, no plans on this. It's really a different story (writing a UrlRule class). It should not conflict with this extension, as we do our tricks here very early in the app life cycle. UrlRules should work as usual - if they simply ignore any locale code in the URL.

**Comment by ustmaestro** [comment]
I found a new strange issue

site.com/ro/blog/post/login is not existing url

with config 
        'urlManager' => [
            'class' => 'yii\web\UrlManager',
		]
		
		is throwing 404

with config 
        'urlManager' => [
            'class' => 'common\components\UrlManager', // your module
		]
		
		is showing post #1

what is wrong

**Comment by ustmaestro** [comment]
someone has tested not existing urls

**Comment by mikehaertl** [comment]
Could you open a new issue with a full report (what is your exact configuration and what do you expect to see), please?

**Comment by ustmaestro** [comment]
OK
