### ISSUE TITLE
Getting 404 with showScriptName=false

### ISSUE THREAD

**Issue by snivs** [codemix/yii2-localeurls#42]
Maybe I misconfigured the app, or don't meet all the minimum requirements.

When I go to "localhost", I am redirected to "localhost/es" and I get a 404 response from the apache server, but when I use showScriptName=true, I'm redirected to "localhost/index.php/es" and the app works.

Here's my UrlManager configuration:

            'class' => codemix\localeurls\UrlManager::className(),
            'enablePrettyUrl'               => true,
            'showScriptName'                => false,
            'enableDefaultLanguageUrlCode'  => true,
            'enableLanguagePersistence'     => true,
            'enableLanguageDetection'       => true,
            'languages'                     => $languages,

**Comment by mikehaertl** [comment]
That's indeed a misconfiguration. If `/es` does not work, then it's an issue with your mod_rewrite setup. Make sure, that really every URL is redirected to `index.php`. That's obviously not the case for you.

**Comment by mikehaertl** [comment]
http://www.yiiframework.com/doc-2.0/guide-start-installation.html#recommended-apache-configuration
