### ISSUE TITLE
How to load supported and default language from database

### ISSUE THREAD

**Issue by tino415** [codemix/yii2-localeurls#43]
Any hint how to load supported language and default language from database ?

**Comment by mikehaertl** [comment]
Uhm, sorry, but please read the Yii 2 guide. This is really basic stuff. I mean, it's simply something like:

```
$languages = Yii::$app->db->createCommand('SELECT code FROM languages')->queryColumn();
```

Or something similar.

**Comment by tino415** [comment]
Ok, but during configuration, I can't use database component or AR, I solved by extending UrlManager...

**Comment by mikehaertl** [comment]
That's one way. If you don't want to extend the class, you could also attach a handler to the ['EVENT_BEFORE_REQUEST`](http://www.yiiframework.com/doc-2.0/yii-base-application.html#EVENT_BEFORE_REQUEST-detail) of the application.

This would also work in the configuration, using this method: 
http://www.yiiframework.com/doc-2.0/guide-concept-configurations.html#configuration-format

**Comment by tino415** [comment]
Thanks.
