### ISSUE TITLE
Allow to set cookie domain for persistance lanuage cookie

### ISSUE THREAD

**Issue by metys** [codemix/yii2-localeurls#48]
There should be an option to set cookie domain, because often multilingual applications uses subdomains for regions. I would like to perserve language information across all subdomains.

**Comment by mikehaertl** [comment]
@metys I've implemented a `languageCookieOptions` property:

> @var array configuration options for the language cookie. Note that `$languageCookieName`
> and `$languageCookeDuration` will override any `name` and `expire` settings provided here.

Can you help testing this please? You can use `'codemix/yii2-localeurls' => '@dev'` in `composer.json` to get the latest dev version from master.

**Comment by metys** [comment]
Thanks! I'll test it later this day...

**Comment by mikehaertl** [comment]
@metys Any news here? I'd prepare a 1.3.0 release - just waiting for you confirmation that everything works as expected.

**Comment by metys** [comment]
Sorry, I was VERY busy last days...
Yes, looks/works good for me.

**Comment by mikehaertl** [comment]
Great. Just released 1.3.0 with this new feature. Thanks!
