### ISSUE TITLE
feature: generate link alternate tags

### ISSUE THREAD

**Issue by AidasK** [codemix/yii2-localeurls#49]
I would be great to generate link tags for each page as well. 
https://support.google.com/webmasters/answer/189077?hl=en

**Comment by mikehaertl** [comment]
Sorry, this is not really the job of this extension. It only deals with URL creation/parsing. If you need those tags, it's not too hard to e.g. add them to your layout file.

**Comment by CyanoFresh** [comment]
please make instruction how to deal with it. What links should be placed in head.
Also I think it should not redirect google bot to it's language by 301 redirect, maybe as option
