### ISSUE TITLE
URL rules per language

### ISSUE THREAD

**Issue by jhebb** [codemix/yii2-localeurls#50]
Hi, great plugin, saves a lot of time!

Is there an easy way to change a URL rule for just a certain language? Since the language gets stripped from the rules array in the config, I wasn't sure the best way to handle this. I'm assuming a custom rule class, but how best to do this without interfering with the plugin?

Ex:
`'rules' => [
    'contact' => 'site/contact',
    '<language:fr>/nousjoindre' => 'site/contact'
]`

**Comment by mikehaertl** [comment]
Sorry, that's currently not possible with the way the extension works. It's unlikely that we ever will support this. The idea was, to keep URL rules completely free of language stuff, so you don't have access to the language parameter at this point.

In your case I'd not use this extension but custom URL rules instead.

**Comment by jhebb** [comment]
@mikehaertl Thanks Mike - any good resources you're aware of to point me in the right direction? I found the guide (http://yii2-cookbook.readthedocs.org/i18n-selecting-application-language/) which was of some help, but that's how i ended up at your plugin!

**Comment by mikehaertl** [comment]
In second thought: Actually a custom [URL rule  class](http://www.yiiframework.com/doc-2.0/guide-runtime-routing.html#creating-rules) should work. In `createUrl()` you get the current language parameter in `language` and in `parseUrl()` the language from URL was already processed and is available in `Yii::$app->language`. Just ignore any language part when creating or parsing any URLs. That's already handled by this extension. Just assume, your URLs had no language parameter at all.

**Comment by jhebb** [comment]
Thanks @mikehaertl I'll give this a try.

**Comment by phuong17889** [comment]
@jhebb have you resolved it?

**Comment by geertw** [comment]
I know this is an old issue, but I was stumbling upon the same problem as @jhebb - I needed to translate the URL patterns themselves (in addition to the language selection, which is already handled very nicely by this extension).

I took the path recommended by @mikehaertl and created a custom URL rule class to parse URL patterns specifically for the current language. This approach works quite well, to save time for others I have open sourced my custom module: https://github.com/geertw/yii2-translatable-url-rule. I use this in addition to yii2-localeurls.

Hope this helps for others!

**Comment by jhebb** [comment]
@geertw That's awesome, seems to work great! Can I ask how you got a language switcher to play nice between the two classes? My current version (based on the example code from this repo) doesn't get a translated version of the url, just adds the language prefix.

**Comment by geertw** [comment]
Yeah, I head to work around some issues with that too. My complete language switcher is [here](https://gist.github.com/geertw/670536de46b401de960282071dfbc1d2), the main point is that you must add **two** variables to set the language:

```php
<?
            $params['language'] = $language;
            $params['url-language'] = $language;
```

The first one is for yii2-localeurls, the second one is for yii2-translatable-url. I can't use the language variable already set for localeurls because it is unset, therefore you have to set it twice. Not the best solution but it works good enough for the language switcher.

**Comment by jhebb** [comment]
@geertw That was the piece I was missing, thanks a bunch!

**Comment by egorsmkv** [comment]
@geertw thanks a lot, man!
