### ISSUE TITLE
Generating urls with enableDefaultLanguageUrlCode = false

### ISSUE THREAD

**Issue by jhebb** [codemix/yii2-localeurls#51]
Is it possible to generate URLs that don't show the default language in the URL? I know they get redirected once they're clicked, but is it possible to create the final url with Url::to()?

eg.

enableDefaultLanguageUrlCode = false
Url::to(['site/index', 'language' => 'en'], true) = http://mysite.com (instead of http://mysite.com/en which redirects to http://mysite.com)

**Comment by mikehaertl** [comment]
If we would detect that and leave it away automatically, you could never create a [reset URL](https://github.com/codemix/yii2-localeurls#reset-to-default-language). As the extension also tries to do not too much magic under the hood, it's up to you to detect that case and leave away the `language` parameter.

**Comment by jhebb** [comment]
Fair enough, that makes sense. Thanks!
