### ISSUE TITLE
Can't set default language via app language

### ISSUE THREAD

**Issue by yoyhosoft** [codemix/yii2-localeurls#54]
Hi,
In app config I set
     'language' => 'th',
and
     'urlManager' => [
            'class' => 'codemix\localeurls\UrlManager',
            'languages' => ['en-US','en','th']
      ]
then open new private window on bowser or clear cache, the to to my site,
url still go to /en-US instead of /th.

it's mean, we can't set default language via app language right?

**Comment by mikehaertl** [comment]
What is the default language configured in your browser? Also check the Yii logs for trace messages of the extension (`YII_DEBUG` must be `true`).

**Comment by yoyhosoft** [comment]
"language configured in your browser" <-- my browser language setting is Thai (it's can change yii default language settings )?

and in app.log after clean and enter website again, it's not appear anything.

Thanks,

**Comment by mikehaertl** [comment]
Make sure, that `YII_DEBUG` is really enabled and that you use the latest version. You should see messages like:

Level | Category | Message
--------|----|-------------
trace | codemix\localeurls\UrlManager::processLocaleUrl |Language code found in URL. Setting application language to 'de'.
trace | codemix\localeurls\UrlManager::processLocaleUrl | Persisting language 'de' in session.
trace | codemix\localeurls\UrlManager::processLocaleUrl | Persisting language 'de' in cookie.

Also make sure, that you check all previous requests. You should see redirect messages there

Level | Category | Message
--------|----|-------------
trace | codemix\localeurls\UrlManager::redirectToLanguage | Redirecting to /de.

**Comment by yoyhosoft** [comment]
8	12:05:28.466	trace	yii\base\Application::bootstrap	Bootstrap with yii\gii\Module::bootstrap()
9	12:05:28.467	trace	codemix\localeurls\UrlManager::processLocaleUrl	Language code found in URL. Setting application language to 'en-US'.

    C:\xampp\htdocs\dusitthanicollege.local\vendor\codemix\yii2-localeurls\UrlManager.php (271)
    C:\xampp\htdocs\dusitthanicollege.local\vendor\codemix\yii2-localeurls\UrlManager.php (165)

10	12:05:28.469	info	yii\web\Session::open	Session started

    C:\xampp\htdocs\dusitthanicollege.local\vendor\codemix\yii2-localeurls\UrlManager.php (273)
    C:\xampp\htdocs\dusitthanicollege.local\vendor\codemix\yii2-localeurls\UrlManager.php (165)

11	12:05:28.469	trace	codemix\localeurls\UrlManager::processLocaleUrl	Persisting language 'en-US' in session.

    C:\xampp\htdocs\dusitthanicollege.local\vendor\codemix\yii2-localeurls\UrlManager.php (274)
    C:\xampp\htdocs\dusitthanicollege.local\vendor\codemix\yii2-localeurls\UrlManager.php (165)

12	12:05:28.472	trace	codemix\localeurls\UrlManager::processLocaleUrl	Persisting language 'en-US' in cookie.

    C:\xampp\htdocs\dusitthanicollege.local\vendor\codemix\yii2-localeurls\UrlManager.php (286)
    C:\xampp\htdocs\dusitthanicollege.local\vendor\codemix\yii2-localeurls\UrlManager.php (165)

**Comment by mikehaertl** [comment]
This is not the first request, because there is obviously already a language code in the URL:

> 9 12:05:28.467 trace codemix\localeurls\UrlManager::processLocaleUrl Language code found in URL. Setting application language to 'en-US'.

You should check the previous request.

**Comment by yoyhosoft** [comment]
Hi,
Before enter site I did as step below:
- Clean browser cookie
- Close all browser
- remove Yii runtime/cache, runtime/HTML
- Restart Apache
- Open browser again, then open new browser in private mode and enter site.

Thanks

**Comment by mikehaertl** [comment]
Again: You need to check the log files for each and every request and try to understand what each message means. When you go to the `/` URL of your website, the extension will detect a language and then redirect. So a second request is made. You should read the log messages from the first request to `/`.

**Comment by yoyhosoft** [comment]
Thanks, I will check and tell you again.

**Comment by yoyhosoft** [comment]
Hi,
I found solution (by debug your code lol...), and solve by

            'enableLanguageDetection' => false,
            'enableDefaultLanguageUrlCode' => true,


Many Thanks for your support.
