### ISSUE TITLE
url problem for codeception acceptance testing

### ISSUE THREAD

**Issue by dataskills** [codemix/yii2-localeurls#58]
Forgive me if this is not the proper place for this issue, please direct me to the proper place if you know where that might be. I am new to acceptance testing with codeception and localeurls. An example of my problem is that I am trying to run an acceptance test on the route "en/about"; the error in codeception says: "Can't be on page "/frontend/web/index-test.php/en/about" "; but when I try this url in a browser it gets rewritten to "en/frontend/web/index-test.php/en/about" which must be the problem since it generates a 404 error. Should I have a separate urlmanager configuration for acceptance tests or something? Have you run into this problem before? Thank you for your consideration.

**Comment by mikehaertl** [comment]
I can't really help you with this as acceptance testing is out of the scope of this library. You can study the test setup that comes with localeurls.

You may also find some ideas in the test setup of our [dockerized yii2 app](https://github.com/codemix/yii2-dockerized). It includes acceptance tests but I've never tried it with localeurls: https://github.com/codemix/yii2-dockerized/wiki/4.-How-to-test
