### ISSUE TITLE
Case sensitivity

### ISSUE THREAD

**Issue by kavolorn** [codemix/yii2-localeurls#59]
Hi there,

Could you please write why you've decided to lowercase language codes? Is not it more consistent to keep ISO 639-1 codes where last part is in uppercase? Is it possible to make an option which will behave as it was before?

I've just noticed many broken links after update (because some parts of code cannot follow redirects).

Appreciate your work!

**Comment by mikehaertl** [comment]
Hmm, I think this was mainly my personal preference for all lowercase URLs. But I guess you have a valid point here. Can you check if my commit above helps you? It adds an option `keepUpperCaseLanguageCode`.

**Comment by kavolorn** [comment]
Thanks! This commit is working for me though consistency is not perfect yet :)

I have prepared table which explains how I see it. 

<table>
    <tr>
        <td></td>
        <td colspan="2">Case sensitivity enabled</td>
        <td colspan="2">Case sensitivity disabled</td>
    </tr>
    <tr>
        <td>Config language</td>
        <td colspan="2">URL language</td>
        <td colspan="2">URL language</td>
    </tr>
    <tr>
        <td></td>
        <td>en-GB</td>
        <td>en-gb</td>
        <td>en-GB</td>
        <td>en-gb</td>
    </tr>
    <tr>
        <td>en-GB</td>
        <td style="background-color:green">VALID</td>
        <td style="background-color:red">now VALID <br/> should 404 <br/> or 302 en-GB</td>
        <td style="background-color:green">302 en-gb</td>
        <td style="background-color:green">VALID</td>
    </tr>
    <tr>
        <td>en-gb</td>
        <td style="background-color:red">now VALID <br/> should 404 <br/> or 302 en-gb</td>
        <td style="color:green">VALID</td>
        <td style="background-color:red">now VALID <br/> should 302 en-gb</td>
        <td style="background-color:green">VALID</td>
    </tr>
</table>

Not sure how hard it is to implement such states (because of additional language detection and maybe other things).

Does it make sence?

**Comment by mikehaertl** [comment]
Config language should never use a lowercase country code, so your line with `en-gb` is not valid IMO. It must always be `en-GB`.

I'm also not sure, if we really should be so strict and issue 404 or 302 in the cases you've shown. Notice that you can also use wildcard patterns like `en-*`. The basic idea was, to make the extension case insensitive with URLs, so that both `en-GB` and `en-gb` work - but the former is redirected by default to make URLs unambiguous.

**Comment by kavolorn** [comment]
Ah, now I understand. I thought that you want to have lowercase codes in configuration also. It is fine how it works now. Thanks for new option!

**Comment by mikehaertl** [comment]
@kavolorn Ok, thanks. I'll create a 1.4.0 release (new feature). Please note that I will rename `keepUpperCaseLanguageCode` to `keepUppercaseLanguageCode` (notice the lowercase `c`). This is more correct as "uppercase" is a single word in english.

**Comment by kavolorn** [comment]
Alright! Thanks :)

**Comment by kavolorn** [comment]
Just noticed that default / url redirects only to lowercase version even keepUppercaseLanguageCode is turned on. Is it a big thing to redirect to uppercase version by default (if option specified)? Thx

**Comment by mikehaertl** [comment]
Confirmed and (hopefully) fixed in 1.4.2 ;)
