### ISSUE TITLE
Support for URL's With Scheme Missing

### ISSUE THREAD

**Issue by denisiodb** [codemix/yii2-localeurls#63]
Does the extension support routes with http:// in the beginning? I have multiple subdomains, so all routes look like this:
`http://sub.domain.com/<controller>/<action>`

But when I create URL's with Url::to(), instead of:
`<a href="http://sub.domain.com/en-US/index/index">`
I get:
`<a href="/en-UShttp://sub.domain.com/index/index">`

Am I missing something? If not, might I suggest for the extension to check if `<language>` is already present in the route so that it won't just prepend it.

**Comment by mikehaertl** [comment]
Can you please show us the code with the arguments to `Url::to()` that you use to create your URLs?

**Comment by mikehaertl** [comment]
@denisiodb The extension also works with absolute URLs, if that's what you mean. Please check the above commit, where I've added some test cases for this.

**Comment by denisiodb** [comment]
I'm not talking about absolute URL's but about routes that include http part. Please try something like:
```
'rules' => [
    'http://foo.fo/<term:.+>/bar' => 'slug/action',
],
```
That's a legitimate route that websites with multiple subdomain's generally have. And the URL you would receive after trying `Url::to(['slug/action', 'language' => 'en-US'])` is `/en-UShttp://foo.fo/<term:.+>/bar` instead of `http://foo.fo/en-US/<term:.+>/bar`.

I'm not sure if Yii's default url manager is smart enough to separate domain and URI so that the extension could insert the language code in between, but if it doesn't, I would suggest to allow manually inserting `<language>` into the route.

**Comment by mikehaertl** [comment]
I see now. It's called [Rules with Server Names](http://www.yiiframework.com/doc-2.0/guide-runtime-routing.html#rules-with-server-names) in the guide. To be honest I'm not sure yet if we will support them here. In any case I'll first need to find some time to think about a solid solution.

If you see an easy way to implement this, feel free to discuss it here or supply a PR. It should not break any of the existing test cases, though.

**Comment by mikehaertl** [comment]
I think we need to do a similar test like in `yii\web\UrlManager` here:

https://github.com/yiisoft/yii2/blob/2.0.7/framework/web/UrlManager.php#L349

**Comment by mikehaertl** [comment]
@denisiodb Can you test if the implementation on master works for you?

**Comment by denisiodb** [comment]
Works fine, thank you very much!

**Comment by mikehaertl** [comment]
@denisiodb Ok, great. Do you happen to run the application in a subdirectory? Because I found some issues with URL creation for the root URL. But it seems to be a Yii problem. Something like this:

```
'http://www.example.com/' => 'site/index',
```

If you use `Url::to(['site/index', 'x' => 'y'])` and `baseUrl` is like `some/directory` you get weird looking URLs like `http://www.example.com?x=y/some/directory`.

**Comment by denisiodb** [comment]
No, fortunately that problem I won't encounter.
