### ISSUE TITLE
Ajax and language redirect

### ISSUE THREAD

**Issue by CyanoFresh** [codemix/yii2-localeurls#66]
Hello. I need to make ajax request (post/get) to my controller action. I use this code:
```
$.ajax({
        "url": 'site/decline-bonus',
        "type": 'post',
});
``` 
It located in widget, in layout
When I am in default language (domain.com/) - there is no problem, but when I change it (domain.com/en) and make ajax call - it redirects browser on that url. How to solve it? Maybe don't redirect ajax requests and detect language by cookie/session?

**Comment by mikehaertl** [comment]
Hmm, can't you create the URL in Yii and pass it to your javascript? In general I find it a bad idea to hardcode URLs in js if you use Yii.

**Comment by CyanoFresh** [comment]
OK, thanks for the answer. Yes, it will be better, but it makes some mess in view files :(
