### ISSUE TITLE
How to render a view when Persistence is off?

### ISSUE THREAD

**Issue by marko85to** [codemix/yii2-localeurls#69]
Hi,
I am trying not to use cookies and I am wondering how can I render a view with the language in use, when I am not using LanguagePersistence?

From my controller's action:
```
public function actionIndex()
    {
     return $this->render('index');
    }
```
always render the english version of the page.

I have tried to use:
```
    public function actionIndex()
    {
     return $this->render('index', [
            'language' => Yii::$app->language
      ])
    }
```
but no luck.

Does the LanguagePersistence necessarily need to be activated? Is there a way to just use the language saved in the session?

Thank you!

**Comment by mikehaertl** [comment]
When persistence is off, the language is still autodetected. Please check here:

https://github.com/codemix/yii2-localeurls#language-detection

**Comment by mikehaertl** [comment]
And if you really want to bypass this extension completely for a single view only, you can always set the application language before rendering:

```
Yii::$app->language = 'de';
return $this->render('index');
```

**Comment by marko85to** [comment]
Thank you for the reply. it's not really what I meant.
Let's assume the first visitor opens the french version of the website:
http://www.example.com/fr/site/index

now the controller will need to render the index page using the code I have mentioned above, and I have noticed that it renders the english version (instead of the french one)
http://www.example.com/en/site/index
is this expected?

I mean, the language was already been passed and I guess it should be on session? (a part from being in the url)

This only happens when persistence is off.

Many thanks
Marco

**Comment by mikehaertl** [comment]
Not sure what you mean. Your URL contains `en`, so of course it will render the english language.

> I mean, the language was already been passed and I guess it should be on session? (a part from being in the url)

If you turn off persistence, then it's not stored in the session.

**Comment by marko85to** [comment]
Sorry I have updated the question, it's more clear now.
It's after a link or redirect to another view

**Comment by mikehaertl** [comment]
Hm, sorry, it's not clear to me. Please provide a full flow: "User opens URL ... User sees a page with a link with URL ... User follows this link and ends up at ..." or something.

**Comment by marko85to** [comment]
Thanks for the reply, I have finally found the answer to my question.

Basically, the option
```
'enableLanguagePersistence' => false
```
disables Cookie and Session.

I just wanted to use the PHP Session and I had to set:
```
'enableLanguagePersistence' => true,
'languageCookieDuration' => false,
```
This allows me to being able to use the language stored in the PHP session (without necessarily using a cookie)

I think you could add this to the documentation as it wasn't really clear for me :-) but thanks for the support!

**Comment by mikehaertl** [comment]
It's already there:

> Persistence
> The last language a visitor has used will be stored in the user session and in a cookie.

and below that:

> languageCookieDuration: How long in seconds to store the language information in a cookie. Set to false to disable the cookie.

**Comment by marko85to** [comment]
sorry and thanks again!
