### ISSUE TITLE
A way to improve loading time

### ISSUE THREAD

**Issue by smilemd** [codemix/yii2-localeurls#72]
Hi,

first of all I want to say a big thanks for this extension and afterward I would like to offer a suggestion. At the moment when page is redirected it's take about 2x time to load the page, maybe there is a way to speed up this process?

Thanks.

![suggestion](https://cloud.githubusercontent.com/assets/6599359/15757211/2ad713a4-290d-11e6-8c1b-97d4c4f73bfb.jpg)

**Comment by mikehaertl** [comment]
Not sure if I understand you right, but during the first visit it of course it takes 2 requests: First there's a request without a language code and then (depending on the configuration) there's a redirect followed by another request. There's nothing we can do about that.

But your page load times look amazingly high. So you should rather find out, why your page is so slow in the first place and try to fix that (caching, etc.). Then the second request won't hurt you so much.
