### ISSUE TITLE
Session "Flash" gets erased when redirecting and using non-default language

### ISSUE THREAD

**Issue by ksweeopo** [codemix/yii2-localeurls#74]
I use the following config:
```
    'language' => 'en',
    'components' => [
        'urlManager' => [
            'class' => 'codemix\localeurls\UrlManager',
            'languages' => [
                'en',
                'ru'
            ],
            'enablePrettyUrl' => true,
            'showScriptName' => false,
            'enableStrictParsing' => true,
            'rules' => [
                '' => 'site/index',
                '<action>' => 'site/<action>'
            ],
        ],
    ],
```
Now, to replicate, set-up 2 Controller Actions:
```
class SiteController extends \yii\web\Controller {
    public function actionIndex() {
        Yii::$app->session->setFlash('test', 'Test', false);
        return $this->redirect('test');
    }    
    public function actionTest() {
        return var_dump(Yii::$app->session->getFlash('test'));
    }
}
```

So, when we direct to http://domain/en or simply http://domain/ , it works as intended and we have ```Test``` outputted.

However, if we go to http://domain/ru , then ```null``` is returned. Surely not an expected behaviour?

**Comment by mikehaertl** [comment]
You pass a string to `redirect()`, so Yii does not create the action URL for you but uses the URL as is. So the extension can not preprocess the URL and add the required language parameters. You should never do this, but always use Yii's [route format](http://www.yiiframework.com/doc-2.0/guide-runtime-routing.html) like `['site/test']` in this case.

**Comment by ksweeopo** [comment]
I see your point! That resolves it. Thanks for your quick help and a great extension!
