### ISSUE TITLE
Double Language identified in url::to

### ISSUE THREAD

**Issue by robov** [codemix/yii2-localeurls#76]
My default language is set to 'english'
So my site is just like /site/page

When I switch to german I see the url: de/site/page (works great)

Now when I create button with url::To
```
    $url = Url::to(['/site/page]);
          echo Html::a(Yii::t('app', 'Delete'), [
                $url]);
```
The url::to generates <code>/de/site/page</code>
Hence the button will go to: <code>de//de/site/page</code> *note the double language

Any suggestions what I am doing wrong?

**Comment by mikehaertl** [comment]
Remove the `[ .. ]` around `$url` as you already have the final URL in `$url`. Actually you could even simplify this to:

`echo Html::a(Yii::t(...), ['/site/page'])`

**Comment by robov** [comment]
Whoa.... that I missed that... thanks... !!!!!!!!
