### ISSUE TITLE
Debug toolbar disappears

### ISSUE THREAD

**Issue by evelinemiranda** [codemix/yii2-localeurls#77]
When I enable the extension in my config, the debug bar magically disappears with YII_DEBUG is set to true.

**Comment by evelinemiranda** [comment]
Still don't know what went wrong, but the debug bar is back after removing my original language switch.

**Comment by mikehaertl** [comment]
Hmm, we had similar reports before, but that should be fixed now. Can you do some more investigation? Like e.g. checking requests in Chrome developer tools. You should see requests to `/debug/default/toolbar?tag=57bc75041cfcc` or similar. Check the status code of these requests and if they maybe redirect somewhere else.
