### ISSUE TITLE
How to configure with http://site.com/base/en

### ISSUE THREAD

**Issue by catiraumihail** [codemix/yii2-localeurls#78]
I'm trying to configure may urls as fallowing:

http://site.com/base/en
http://site.com/base/en/controller/action
http://site.com/base/en/module/controller/action
but this seems not working.

Can you please check what is wrong and add some examples of using links like that.

PS. UrlManager can't resolve requests prefixed by baseUrl

**Comment by mikehaertl** [comment]
Is your application installed in `/base`? It must be the root directory of your application. If unclear: `Yii::$app->request->baseUrl` should return `/base` in your case.

Actually the extension should then work out of the box - no extra configuration required. There are even test cases for this. I have to admit, that I've never tested in a real setup - so the test cases may be completely broken and you're the first person who's using a installation with base URL. But I actually think that's quite unlikely. You can check you the test cases in the `tests/` directory. Specifically the `*WithBaseUrlTest.php` files.

**Comment by mikehaertl** [comment]
Also what exactly do you mean by "configure my urls"? Do you mean you add URL rules or something? If so, that will not work. The language prefix always comes first. Unless - as explained above - your application really lives in a subdirectory `/base` in your web root.

**Comment by catiraumihail** [comment]
In my case i configure yii2-advanced application like fallowing:
http://prntscr.com/cklo13
public_html - holds frontend web
public_html/manager - holds backend web

with frontend urls  accesible at `http://site.com/en` configured with this url manager have no problems
problems is when i configure `http://site.com/manager/en`

**Comment by catiraumihail** [comment]
Maybe problems is with htacces?
htacces frontend
http://prntscr.com/cklr52

htacces backend
http://prntscr.com/cklrtt

**Comment by catiraumihail** [comment]
I made some debugs

added a var_dump($request) in UrlManager just after  `public function parseRequest($request)` function

when hit http://site.com/manager  `$request->__baseUrl = '/maner'`
when hit http://site.com/manager/en  `$request->__baseUrl = ''`

so when it redirects baseUrl is empty

**Comment by catiraumihail** [comment]
UrlManager configuration for manager
http://prntscr.com/ckm06v

Any ideea what I'm doing wrong?

**Comment by mikehaertl** [comment]
Sorry, but I find your setup very confusing. Actually I can not help you configure the rewrite rules for your app. All I know is, that this extension basically works. It seems you do nifty stuff like nesting applications or something. In that case it's up to you to find a proper configuration.

If you think, something is broken, then please provide a simple (!!) example configuration so that I can reproduce the issue.

**Comment by catiraumihail** [comment]
Nested apps is very usefull when you have only one domain and no way to create subdomains


Here are some screenshots of requests that i've made maibe it will help
http://prntscr.com/ckm80u  - without language
http://prntscr.com/ckm6mb - with language

Problem is when is redirected from `site.com/manager` to `site.com/manager/en`
$request->__baseUrl is empty and page fails
instead of creating url whith baseUrl it creates without it and is moving to one level up

**Comment by mikehaertl** [comment]
> Nested apps is very usefull when you have only one domain and no way to create subdomains

In that case I'd rather create a module. Like I said: Nested apps make things complex - which you already see from the issues you have. They are only caused by getting the rewrite rules correct. I can't help you with this.

**Comment by catiraumihail** [comment]
Thanks man! I figured out what is wrong with may app. Problem was as I mentioned before with htacces file
http://prnt.sc/cklrtt

`RewriteRule . /index.php`  => `RewriteRule . index.php`

now all works perfectly. Slash before index.php cause a half day of debugs and a bunch of nerves. :)

Thank you for doing great job and for your support!
