### ISSUE TITLE
 PHP Fatal Error – yii\base\ErrorException Class 'LanguageDropdown' not found

### ISSUE THREAD

**Issue by mutyii** [codemix/yii2-localeurls#8]
I'm using the yii 2.0.3 advanced template and
1) I've installed the yii2-localurls extension using composer.
2) I've added  `namespace app\components; ` at the top of the LanguageDropdown class
3) I've put the `LanguageDropdown` class in my `components` folder 
4) I've made all the adjustments in the config files as indicated
and on my form
5) I've added a ` use yii\bootstrap\Dropdown; ` statement
6) when I call the LanguageDropdown like this: ` <?php echo LanguageDropdown::widget([]); ?>`,
I get:  `PHP Fatal Error – yii\base\ErrorException Class LanguageDropdown not found`.
I was expecting a dropdown with languages to show up so that when I select one,  the corresponding
url is triggered.
I think this is not an issue with this beautiful extension as such, but rather because of my weak programming skills. What I need is a simple dropdown language switcher widget.
What am I missing? Can please someone help me here?

Thanks in advance and apology for my weak programming skills.

**Comment by mikehaertl** [comment]
The language dropdown widget is not part of this extension. You can find an example in the README.

**Comment by mikehaertl** [comment]
You're probably missing a `use app\components\LanguageDropdown` in your view file.

Sorry, but I can't really give you any further support in such basic things. Please only use the issues here for problems related to this extensions.
