### ISSUE TITLE
jQuery function conflict with this extension. Please help me!

### ISSUE THREAD

**Issue by makeloo** [codemix/yii2-localeurls#84]
$(document).ready(function(){
    $.ajax({
        url: '/order/explore',
        type: 'POST',
        success: function(res){
            if(res){
                //console.log(res);
                showOrder(res);
            } else {
                return;
            }
        }
    });

});

Hello friends. This jquery function conflict with extension. When i change language from default it redirect me to "/languagecode/order/explore" Please help me: what i need change in this function?

**Comment by makeloo** [comment]
Dear friends. I have find this issue https://github.com/codemix/yii2-localeurls/issues/66   my problem is very similar... I tried use yii for generate link in javascript. Like this: 
`$.ajax({
            url: "<?= Url::to('/order/add') ?>",
            type: 'GET',
            success: function (res) { 
                console.log(res)
        });`
but it dousnt work.

**Comment by mikehaertl** [comment]
This is not a problem of the library. Use correct URLs and you should not see any redirects. I can not help you generate your js code.

**Comment by makeloo** [comment]
url: "<?= Url::to(['/order/add']) ?>",     use this it s okey)))
