### ISSUE TITLE
baseUrl and enableDefaultLanguageUrlCode problem

### ISSUE THREAD

**Issue by harrytang** [codemix/yii2-localeurls#87]
Steps to Reproduce:

1. set enableDefaultLanguageUrlCode = true
2. set baseUrl = https://domain.com
3. Yii::$app->urlManager->createUrl(['controller/action']);

Expected: https://domain.com/en-us/controller/action
Result: https://domain.comhttps//domain.com/en-us

**Comment by mikehaertl** [comment]
Why would you set the `baseUrl` to `https://domain.com`? The base URL is the relative URL of your application. And you should not have to set it at all.

http://www.yiiframework.com/doc-2.0/yii-web-request.html#$baseUrl-detail

**Comment by harrytang** [comment]
I have a console application that sending email to users (there is URLs in email). As I know, you must set baseUrl when using console app.

**Comment by mikehaertl** [comment]
Yes, but you have to set the URL in `hostInfo` not in `baseUrl`. Unless you've installed in a subdirectory of webroot you also need to set `baseUrl` to an empty string.

Here's how I do it:

```
'components' => [
    'urlManager' => [
        // ... snip ...
        'hostInfo' => 'https://domain.com',
        'baseUrl' => '',
```

**Comment by harrytang** [comment]
That works fine for the console, thanks.

But it doesn't work for subdomain. I have https://backend.domain.com and from backend I set:
```
'urlManagerFrontend' => [
            // ... snip ...
            'hostInfo' => 'https://domain.com'
            'baseUrl'=> '',
        ],
```
Yii::$app->urlManagerFrontend->createUrl(['controller/action']) will generate https://**backend**.domain.com/....

**Comment by mikehaertl** [comment]
Sorry, but this is no longer related to this extension. If you have problems with URL creation from console please try the usual Yii 2 support chanels.

**Comment by mikehaertl** [comment]
One more note: You need to make sure, that you set `hostInfo` and `baseUrl` only for console applications! It should not be part of your web configuration.

**Comment by harrytang** [comment]
console works fine, only subdomain webapp. Thank you :)
