### ISSUE TITLE
www , non-www redirects

### ISSUE THREAD

**Issue by luys** [codemix/yii2-localeurls#88]
I'm having a trouble with www , non-www redirects.

I've implemented a simple redirect in frontend/web/.htaccess:
RewriteCond %{HTTP_HOST} ^yourdomain.com [NC]
RewriteRule ^(.*)$ http://www.yourdomain.com/$1 [L,R=301]

With this configuration the website does not work as expected. For example:
When I try to access http://www.yourdomain.com/en/seminars/view?id=25 without www, I've got redirected to http://www.yourdomain.com/index.php/seminars/view?id=25 - where I see the text "No input file specified." on a white page.

**Comment by mikehaertl** [comment]
Hmm, I'm sorry, but I can't see what this has to do with our extension. The error message is an Apache error message, so you don't even reach the Yii application. You rather have a problem with setting up the correct rewrite rules. I can't help you with that, please consult the usual support channels: stackoverflow etc.
