### ISSUE TITLE
redirect loop with advanced application template

### ISSUE THREAD

**Issue by h07r0d** [codemix/yii2-localeurls#9]
Just pulled master, looks like a very helpful extension.

Once I'm setup on frontend (local vhost), I just get a redirect loop back to frontend.  here's my config/main.php:

    'bootstrap' => ['log', 'codemix\localeurls\LocaleUrls'],
    'localeUrls' => [
      'class' => 'codemix\localeurls\LocaleUrls',
      'enableDefaultSuffix' => true,
      'enableLanguageDetection' => false,
      'enablePersistence' => false,
      'languages' => ['en', 'fr'],
    ],
    'urlManager' => [
      'class' => 'codemix\localeurls\UrlManager',    		
      'enablePrettyUrl' => true,
      'showScriptName' => false    		
    ],

I cleared any persistence that may have stuck around, but any request to http://frontend, which should redirect to http://frontend/en is just looping back to http://frontend.

**Comment by mikehaertl** [comment]
Are you sure, you have set the `language` parameter of your application? It should be `en` in your case.

**Comment by h07r0d** [comment]
Yes, language as en in the frontend config as well

**Comment by mikehaertl** [comment]
Then can you do some debugging? The code is not very hard. Maybe start at this line:
https://github.com/codemix/yii2-localeurls/blob/master/LocaleUrls.php#L147

What is `$this->_defaultLanguage` (should be `en`)? The following lines should also be easy to debug. Maybe you find out, why the wrong redirect URL is created.

**Comment by h07r0d** [comment]
`$this->_defaultLanguage` is empty, and `$language` is unitialized.  I'm trying a debug session for url frontend/site/about

**Comment by h07r0d** [comment]
Once I get into processRequest() from init(), I notice that $this->languages is empty. Then that makes the local $languages array empty, which gives a match all for the preg_match.  Then line 104 sets Yii::$app->language to an empty string, hence the redirect loop.

Not sure why $this->languages is empty though, as this is during the bootstrap process, and I've added LocaleUrls to the bootstrap array.

**Comment by mikehaertl** [comment]
Hmm, are you sure, that you have used the correct config files? `$this->languages` really should never be empty with your above configuration.

**Comment by h07r0d** [comment]
yup, I've got my i18n config done in common/config/main.php and the localeurl setup in frontend/config/main.php, both of which have a default language set, but only frontend config has the localeUrls language array.

**Comment by h07r0d** [comment]
oh, that was through the bootstrap run, not the actual url build, my bad. on the actual processing, I have `$this->languages = ['en','fr']` which makes `$pattern` set to 'en|fr'.

preg_match is "succeeding" since I get into the if statement (line 101) but $m is empty, which then sets $language to '' (line 103) and again sets app->language to ''

**Comment by mikehaertl** [comment]
> preg_match is "succeeding" since I get into the if statement (line 101) but $m is empty, which then sets $language to '' (line 103) and again sets app->language to ''

This doesn't make sense. If you enter without a language code in URL, the regular expression `^(en|fr)\b(/?)` can not match. And after the redirect to `/en` you will find `en` in `$m[1]`. There would also be no redirect loop in this case, because the only `redirect()` in the upper if block is skipped in line 120.

> so the bootstrap run ends up setting Yii::$app->language to '', which in the 2nd run ends up getting $this->_defaultLanguage to ''

I'm still pretty sure, that your configuration must be messed up somehow. If you set `language` in your application, it can not be empty during bootstrap. An empty language would also explain the endless loop.

**Comment by h07r0d** [comment]
ya, i'm leaning towards some kind of misconfiguration too, but both common/config/main.php and frontend/config/main.php have a 'language' => 'en' line in them.  Only the frontend config has the localeUrls and custom UrlManager config, which is copy/pasted in first comment.  The only difference is the bootstrap line, your setup instructions list it as

    'bootstrap' => ['localeurls']

which doesn't work, I get a "cannot find component" error.  However, changing it to

    'bootstrap' => ['codemix\localeurls\LocaleUrls']

clears that error.

Tried another run debugging frontend/en to see what happens:

On the bootstrap side of the debug run, `Yii::$app->language` is set to 'en' on line 73, so `$this->_defaultLanguage` gets set to 'en' as well.  Then stepping into `$this->processRequest()` on line 97 the `$this->languages` is empty, which means $pattern goes empty, thus giving the preg_match access to lines 103, and setting $language to `empty`.

Then the second run though after bootstrapping has `Yii::$app->language` set to `empty`.

So it seems that there's something going on with the bootstrapping.

**Comment by mikehaertl** [comment]
Ok, here we have something:

    'bootstrap' => ['localeUrls']

This *must* work! But note the upper case `U`! The [bootstrap](http://www.yiiframework.com/doc-2.0/yii-base-application.html#$bootstrap-detail) option accepts a component ID. So if you have configured everything right, `localeUrls` is a valid component ID.

**Comment by h07r0d** [comment]
)(*&)*&%@!(*&^$(*^&^%!#@&^%$!^%#~@  Yup, that was it.  I **hate** those so much!  Sorry for so much wasted time, but thanks a tonne for the support anyway :)
