### ISSUE TITLE
Missing redirects when using UrlNormalizer

### ISSUE THREAD

**Issue by xr0m3oz** [codemix/yii2-localeurls#90]
Version 1.4
```
		'urlManager' => [
			'class' => 'codemix\localeurls\UrlManager',
			'suffix' => '/',
			'normalizer' => [
				'class' => 'yii\web\UrlNormalizer',
				// use temporary redirection instead of permanent for debugging
				'action' => \yii\web\UrlNormalizer::ACTION_REDIRECT_PERMANENT,
			],
			'languages' => ['en','ru','uk'],
			'enablePrettyUrl' => true,
			'showScriptName' => false,
			'rules' => [
			],
		],
```
Once connected, the configuration normalizer and a suffix, all starnitsy work properly if you enter the address at the end without the "/" is going to redirect slash.

But it does not work for the main page with the language.
Example 
site.com/site/faq will redirect to site.com/site/faq/
site.com/en NOT REDIRECT to site.com/en/

And this is bad because the turns 2 are absolutely the same home page.

**Comment by mikehaertl** [comment]
The current implementation interferes with the implemenation of `UrlNormalizer` (which IMO sucks big time). I try to work on it.

But can you do me a favour and check if URL normalizer works without our class?

```
        'urlManager' => [
            'suffix' => '/',
            'normalizer' => [
                'class' => '\yii\web\UrlNormalizer',
                'action' => \yii\web\UrlNormalizer::ACTION_REDIRECT_TEMPORARY,
            ],
            'enablePrettyUrl' => true,
            'showScriptName' => false,
        ],
```

I would expect that this gives me redirects from `http://localhost` to `http://localhost/`. But it doesn't:

```
$ curl -I http://localhost:8080
HTTP/1.1 200 OK
Date: Wed, 22 Feb 2017 15:03:35 GMT
Server: Apache/2.4.10 (Debian) PHP/7.0.8
X-Powered-By: PHP/7.0.8
Expires: Thu, 19 Nov 1981 08:52:00 GMT
Cache-Control: no-store, no-cache, must-revalidate
Pragma: no-cache
Content-Type: text/html; charset=UTF-8
```

Other URLs get redirected as expected:

```
$ curl -I http://localhost:8080/site/login
HTTP/1.1 302 Found
Date: Wed, 22 Feb 2017 15:04:03 GMT
Server: Apache/2.4.10 (Debian) PHP/7.0.8
X-Powered-By: PHP/7.0.8
Location: http://localhost:8080/site/login/
Content-Type: text/html; charset=UTF-8
```

Is this a bug or a feature of `UrlNormalizer`?

**Comment by xr0m3oz** [comment]
On another site launched **http://localhost** but there by default as the browser itself has added a slash at the end. Before normalayzer installation.

After the installation **normalizer** is also doing a redirect, but it is not visible when you press F12 Network in chrome

**Comment by mikehaertl** [comment]
I'd recommend to do tests with `curl` on the command line, so that you really see what is going on. I still think, that there's no redirect for the home URL.

Anyway: I've pushed a fix do master that makes at least the URLs with language code behave as expected. Can you help testing please?

**Comment by xr0m3oz** [comment]
Removing codemix/yii2-localeurls (1.4.5)
  - Installing codemix/yii2-localeurls (1.4.6)
    Downloading: 100%

I updated but also redirect not working
http://localhost/en  not redirect to http://cashback.loc/en/

**Comment by mikehaertl** [comment]
There's no new release. The change is not in 1.4.6. Simplest way to test is to manually download the `UrlManager.php` from here: https://raw.githubusercontent.com/codemix/yii2-localeurls/master/UrlManager.php

**Comment by xr0m3oz** [comment]
Yes so it works. http://localhost/en Redirect to http://cashback.loc/en/
 You could add to the composer?

**Comment by mikehaertl** [comment]
Thanks. I've just created release 1.4.7 with this fix included. So you should be able to install with composer now. If it's not pulling the latest version, try again after some time. Composer caches some things.

**Comment by xr0m3oz** [comment]
https://localhost/en/sitemap.xml is redirect to https://localhost/en/sitemap.xml/
Maybe you know how to fix it?

**Comment by mikehaertl** [comment]
That's not an issue of this library I think. It's what UrlNormalizer does, because that's what you configured. You should ask the Yii 2 support.
