### ISSUE TITLE
$this->normalizer property exists since yiisoft/yii2 2.0.10!

### ISSUE THREAD

**Issue by Quexer69** [codemix/yii2-localeurls#91]
https://github.com/yiisoft/yii2/blob/master/framework/web/UrlManager.php#L148

Therefore your composer constraint 
`"yiisoft/yii2": "*"` 
should be changed to 
`"yiisoft/yii2": ">= 2.0.10"`

otherwise you can install this package in version `1.4.7` with `yii2 < 2.0.10` and will get

`Getting unknown property: codemix\localeurls\UrlManager::normalizer`

**Comment by mikehaertl** [comment]
Ah, thanks. I'll better fix this so that it also works if this property doesn't exist.

**Comment by mikehaertl** [comment]
@Quexer69 Pushed a fix. Could you maybe verify if this works for you?

**Comment by Quexer69** [comment]
Yes, or just check for the property to exist

**Comment by Quexer69** [comment]
Thanks, it works!

I´ll close my PR for that.

Cheers!

**Comment by mikehaertl** [comment]
Great, thanks. Just released 1.4.8 with this fix.
