### ISSUE TITLE
Option to not redirect loading url without lang code, when user is not on default language (if 'enableDefaultLanguageUrlCode' => true,)

### ISSUE THREAD

**Issue by Matvik** [codemix/yii2-localeurls#96]
It would be great to have an option, that turns on mode:
Default language is always without language code, and if user is currently on other language, typing URL without lang code loads default language (currently he will be redirected to the current language). Lot of sites has such behaviour. Thanks!

**Comment by mikehaertl** [comment]
Hmm, your description is a bit confusing to me. In the title you say `enableDefaultLanguageCode` should be `true` - but in the issue text you say "default language is always without language code".

**Comment by Matvik** [comment]
Sorry, i was mistaken. I mean, enableDefaultLanguageUrlCode => false, and if user loads page without lang parameter in url, current language will be switched to default and he gets the page on default language. Now he will be redirected to the current language in this case.

**Comment by Matvik** [comment]
The point of this proposition is to make strong congruence between urls without language parameters  and default language independent of the current language and other things.

**Comment by mikehaertl** [comment]
After some thinking I would say, that's what you get if you set `enableLanguagePersistance` and `enableLanguageDetection` both to `false`.

Both features are on by default and work like this: If there's no language code in the URL then the user is redirected either to the language stored in session/cookie (persistence) or - if none - the language that is auto detected from the browser settings.

Now if we should no longer redirect if there's no language in URL you can't use the above features anymore. If you turn them off, the only redirects left would be e.g. from `/en/site/page` to `/site/page` if your default language is `en`. I've added some tests for this configuration and it seems to work as expected. See here: https://github.com/codemix/yii2-localeurls/blob/master/tests/RedirectTest.php#L206

**Comment by Matvik** [comment]
Yes! It really works, as expected! I think, it will be great to describe this case in documentation)

**Comment by mikehaertl** [comment]
Well, there are so many different combinations of configuration that each make the extension behave quite differently. I'm not sure if we can add them all to the (already lengthy) documentation. But I'll consider adding something.
