### ISSUE TITLE
UrlManager and UrlNormlizer

### ISSUE THREAD

**Issue by xr0m3oz** [codemix/yii2-localeurls#99]
https://github.com/codemix/yii2-localeurls/issues/90

You have made a correction in the code.
```
                if (property_exists($this, 'normalizer') && $this->normalizer!==false) {
                    parent::parseRequest($request);
                }
```
http://site.loc/en/sitemap.xml  redirect to http://site.loc/en/sitemap.xml/

But I found another option as much as possible to get rid of the normalization of certain addresses.
In UrlManager in rules add
```
			'rules' => [
				[
					'pattern' => 'sitemap',
					'route' => 'sitemap/default/index',
					'suffix' => '.xml',
					'normalizer' => false,
				],
			],
```
'normalizer' => false,  

And it helped. Only if you comment out the code that you added as a fix.

**Comment by mikehaertl** [comment]
It's a bit unclear what this issue is about. Do you talk about the latest changes from #94 and #97 which are currently on master (no release yet)? Is there a new problem now?

**Comment by xr0m3oz** [comment]
No, about version last version on composer.

**Comment by mikehaertl** [comment]
Ok, closing this then, because we've refactored the whole logic around `UrlNormalizer`. Will create a new release now. If you still find something is broken feel free to leave another comment.
